### ISSUE TITLE
daps: Generate TAB completion [sf#10]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#10]
**Reported by tom_schr on 2011-12-16 12:28 UTC**
Create completion script for options and subcommands

Here are some links:
- http://www.caliban.org/bash/
- http://www.debian-administration.org/articles/316
- http://www.debian-administration.org/articles/317
- http://www.linuxjournal.com/content/more-using-bash-complete-command

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2013-04-11 20:45**
- **Milestone**: 2.0 --> Future

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2013-04-11 20:45**
Moving to Future, I do not think this will make 2.0.

**Comment by fsundermeyer** [comment]
Has been fixed with DAPS 2.3.0
