### ISSUE TITLE
Make it possible to vacuum SVG's from within DAPS [sf#100]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#100]
**Reported by sknorr on 2012-08-30 15:17 UTC**
Similar to PNG which can be optimised with optipng, Unused elements in SVG files can be removed with

inkscape --vacuum-defs

It might be a good idea to support something like "daps vacuum-svg" which would just run Inkscape over all the SVG source files.

There are more aggressive SVG optimisers available, but given that those often change the structure of the file itself, we might not want to use them. For an example, see: https://launchpad.net/svg-cleaner

**Comment by tomschr** [comment]
**Updated by sknorr on 2012-08-31 07:39**
- **priority**: high --> medium

**Comment by fsundermeyer** [comment]
SVGs usually occupy very little space (38 images for SLE only occupy 1.4 MB), so I do not think it's worth implementing this as a feasture in DAPS. If needed, this should be taken into account when creating the SVGs.
