### ISSUE TITLE
Decide Strategy for Input and Output Directory of CSS, JS, and other Ressources [sf#109]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#109]
**Reported by tom_schr on 2012-12-06 10:16 UTC**
For online formats like HTML, the DocBook stylesheets use these external resources and parameters:
- CSS files for styling (html.stylesheet, and docbook.css.source, custom.css.source)
- possible JavaScript files (html.script)
- navigation images (navig.graphics.path)
- admonition images (admon.graphics.path)
- callout images (callout.graphics.path)

These files are used inside HTML files. To customize, the [DocBook HTML stylesheets](http://docbook.sourceforge.net/release/xsl/current/doc/html/index.html) contain the following parameters

| Parameter | Description | Default Value |
| --- | --- | --- |
| [<tt>html.stylesheet</tt>](http://docbook.sf.net/release/xsl/current/doc/html/html.stylesheet.html) | Name of the stylesheet(s) to use in the generated HTML | empty |
| [<tt>docbook.css.source</tt>](http://docbook.sf.net/release/xsl/current/doc/html/docbook.css.source.html) | Name of the default CSS input file | <tt>docbook.css.xml</tt> |
| [<tt>custom.css.source</tt>](http://docbook.sf.net/release/xsl/current/doc/html/custom.css.source.html) | Name of a custom CSS input file | <tt>docbook.css.xml</tt> |
| [<tt>html.script</tt>](http://docbook.sf.net/release/xsl/current/doc/html/html.script.html) | Name of the script(s) to use in the generated HTML | empty |
| [<tt>navig.graphics.path</tt>](http://docbook.sf.net/release/xsl/current/doc/html/navig.graphics.path.html) | Path to navigational graphics | <tt>images/</tt> |
| [<tt>admon.graphics.path</tt>](http://docbook.sf.net/release/xsl/current/doc/html/admon.graphics.path.html) | Path to admonition graphics | <tt>images/</tt> |
| [<tt>callout.graphics.path</tt>](http://docbook.sf.net/release/xsl/current/doc/html/callout.graphics.path.html) | Path to callout graphics | <tt>images/callouts/</tt> |

Additional parameter which influences the output too:

| Parameter | Description | Default Value |
| --- | --- | --- |
| [<tt>base.dir</tt>](http://docbook.sf.net/release/xsl/current/doc/html/callout.graphics.path.html) | The base directory of chunks | empty |

For CSS, there are now two methods to use CSS file:
- with the html.stylesheet parameter
- with the docbook.css.source and custom.css.source parameters

All of the above parameters contain an (implicit) directory structure which reflects also inside the HTML sources.

**Comment by tomschr** [comment]
**Commented by tom_schr on 2012-12-06 10:23**
Added testcase. 
1. Unpack to /tmp. This creates a dbxslt directory.
2. Change directory to somewhere else 
3. Run xsltproc with

```
$ xsltproc --output html/foo.html /tmp/dbxslt/xhtml/docbook.xsl foo.xml
```

This creates the following output:

```
Writing css/docbook.css for article(...)
Writing css/../static/css/foo.css for article(...)
```

TODO: find out which strategy we should choose:
- Define the input (custom.css.source) only as filename and define input and output parameters with directory content (or assume input stays always in the same location; could be make sense, if we assume static/css/) OR
- Allow for the input also a directory path and split off the directory part; concat it with the target path.

**Comment by tomschr** [comment]
**Updated by tom_schr on 2012-12-06 10:31**
- **summary**: Provide directory structure for input and output of CSS, JS, and other Ressources --> Decide Strategy for Input and Output Directory of CSS, JS, and other Ressources

**Comment by tomschr** [comment]
**Updated by tom_schr on 2012-12-06 15:10**
- **labels**: xhtml, html, daps --> xhtml, html, daps, css

**Comment by fsundermeyer** [comment]
Was fixed quite some time ago by introducing and supporting a static/ directory for the stylesheets.
