### ISSUE TITLE
Generate daps-devel subpackage [sf#120]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#120]
**Reported by tom_schr on 2013-01-22 08:07 UTC**
It would be nice to have a daps-devel subpackage. 

This can include some helper scripts to create your own customization layers or further documentation on how to develop stylesheets.

**Comment by ghost** [comment]
I don't think we have either helper scripts for customization layers or documentation on creating stylesheets. Before we do, this issue does not make sense.
