### ISSUE TITLE
Check whether logging can be improved using named pipes [sf#130]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#130]
**Reported by fsundermeyer on 2013-02-18 09:13 UTC**
The log file currently contains the same information as is being printed to STDOUT, This is not helpful if the verbosity level is 0 or 1.
Check whether a combination of tee and named pipes can solve this issue.
- https://en.wikipedia.org/wiki/Named_pipe
- http://www.linuxjournal.com/article/2156

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-02-18 12:34**
- **labels**:  --> daps
- Description has changed:

Diff:

```

--- old
+++ new
@@ -1,4 +1,5 @@
 The log file currently contains the same information as is being printed to STDOUT, This is not helpful if the verbosity level is 0 or 1.
 Check whether a combination of tee and named pipes can solve this issue.

-https://en.wikipedia.org/wiki/Named_pipe
+* https://en.wikipedia.org/wiki/Named_pipe
+* http://www.linuxjournal.com/article/2156

```

**Comment by fsundermeyer** [comment]
Not possible - with bash tghis problem cannot be solved.
