### ISSUE TITLE
Import images [sf#132]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#132]
**Reported by fsundermeyer on 2013-02-26 12:58 UTC**
To lower the hurdle for newbies, introduce a target to import one or more images to a project.
The target should copy the image(s) to the appropriate directory under images/src and check for "uniqueness".

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-12-03 09:23**
- **labels**:  --> doc

**Comment by fsundermeyer** [comment]
I do not see any additional value in this - whether I specify paths to images oin the daps command line or with `cp` actually makes little differences... WONTFIX
