### ISSUE TITLE
Add the option to copy logs to another directory from daps-auto.pl [sf#150]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#150]
**Reported by sknorr on 2013-04-18 11:51 UTC**
For the internal docserv server, it would be great if we had DAPS's logs available. Since the documentation on docserv is served via a normal web server that looks for index.\* files, we probably don't want the logs to be in the same folder as the books themselves. (For reasons of discoverability).

I would propose instead adding logs to a new top-level directory "logs" with a directory structure similar to

```
logs/[name of deliverable]/[language]/[single-html|html|pdf]--[YYYY]-[MM]-[DD]--[fail|success].log
```

**Comment by tomschr** [comment]
**Commented by sknorr on 2013-04-18 11:52**
- Description has changed:

Diff:

~~~~

--- old
+++ new
@@ -2,4 +2,4 @@
 
 I would propose instead adding logs to a new top-level directory "logs" with a directory structure similar to
 
-    logs/[name of deliverable]/[language]/[single-html|html|pdf]/[YYYY]-[MM]-[DD]--[fail|success].log
+    logs/[name of deliverable]/[language]/[single-html|html|pdf]--[YYYY]-[MM]-[DD]--[fail|success].log

~~~~

**Comment by fsundermeyer** [comment]
Closing as invalid, since daps-auto.pl has been replaced by daps_autobuild. The latter does not write logfiles anymore, but rather sends failure alerts by mail.
