### ISSUE TITLE
Support language specific time stamps with stylesheets [sf#152]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#152]
**Reported by fsundermeyer on 2013-05-21 14:24 UTC**
Seems like not all SUSE stylesheets support a language specific date format (the flyer stylesheet definetely does not). If no "format" attribute is specified with the <?dbtimestamp?> PI, the stylesheets should automatically generate a correct date format:

Here are dbtimestamps we use, none of which are the same as the
English:

DE      <?dbtimestamp format="d. B Y"?>
ES      <?dbtimestamp format="d de B de Y"?>
FR      <?dbtimestamp format="d B Y"?>
IT      <?dbtimestamp format="d B Y"?>
JA      <?dbtimestamp format="Y"?> 年 <?dbtimestamp format="B"?>月 
<?dbtimestamp format="d"?> 日
KO      <?dbtimestamp format="Y"?>년 <?dbtimestamp format="B"?>월 
<?dbtimestamp format="d"?>일
PT-BR   <?dbtimestamp format="d de B de Y"?>
ZH-CN   <?dbtimestamp format="Y"?> 年 <?dbtimestamp format="B"?> 月 
<?dbtimestamp format="d"?> 日
ZH-TW   <?dbtimestamp format="Y"?> 年 <?dbtimestamp format="B"?>月 
<?dbtimestamp format="d"?> 日
AR      <?dbtimestamp format="d B Y"?>
CZ      <?dbtimestamp format="d. B Y"?>
HU      <?dbtimestamp format="Y. B d."?>
PL      <?dbtimestamp format="d B Y"?>
RU      <?dbtimestamp format="d B Y"?>

Thomas, Stefan:
Please check with the existing formats:
DocBook:
grep \
datetime /usr/share/xml/docbook/stylesheet/nwalsh/current/common/*.xml

DAPS:
grep -A1 datetime suse/xslt/common/l10n/*.xml

And adjust the latter, if needed.

**Comment by tomschr** [comment]
**Commented by tom_schr on 2013-05-22 14:32**
This should be fixed now in [r3139]. Current situation:
- If no <tt>date</tt> element is inserted inside <tt>articleinfo</tt>, the current localized date is added to the titlepage.
- If <tt>date</tt> is given and contains text, this text is used.
- If <tt>date</tt> is given and contains a <tt>&lt;?dbtimestamp?&gt;</tt> PI, the current, localized date is added.
- If <tt>date</tt> is given and contains a <tt>&lt;?dbtimestamp format="..."?&gt;</tt> PI, the date is added as definied by the format pseudo-attribute.

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-05-22 14:32**
- **status**: open --> needinfo
- **Info Provider**: Frank Sundermeyer

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-05-28 11:45**
- **status**: needinfo --> closed

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2013-05-29 13:05**
- **status**: closed --> open

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2013-05-29 13:05**
Re-Opening: This is also needed for 
- pocket 
- "normal" fo,
- html
- html-single

If done, please re-assign to sknorr to make sure these changes also go into the new stylesheets.

After that, re-assign to me so I can adjust the XML sources accordingly.

**Comment by tomschr** [comment]
**Commented by tom_schr on 2013-05-29 18:49**
Did a quick look:
- "Normal" FO: Open suse/xslt/fo/booktitlepage.xsl, change line 56 to
  
  <pre>
  &lt;xsl:apply-templates select="self::book/bookinfo/date" mode="book.titlepage.recto"/>
  </pre>
  
  Add the following new template to suse/xslt/fo/booktitlepage.xsl:
  
  <pre>
  &lt;xsl:template match="bookinfo/date" mode="book.titlepage.recto">
  &lt;xsl:variable name="pi"  select="processing-instruction('dbtimestamp')"/>
  &lt;xsl:variable name="format">
    &lt;xsl:variable name="pi-format">
      &lt;xsl:call-template name="pi-attribute">
        &lt;xsl:with-param name="pis" select="$pi"/>
        &lt;xsl:with-param name="attribute">format&lt;/xsl:with-param>
      &lt;/xsl:call-template>
    &lt;/xsl:variable>
    &lt;xsl:choose>
      &lt;xsl:when test="$pi-format != ''">
        &lt;xsl:value-of select="$pi-format"/>
      &lt;/xsl:when>
      &lt;xsl:otherwise>
        &lt;xsl:call-template name="gentext.template">
          &lt;xsl:with-param name="context" select="'datetime'"/>
          &lt;xsl:with-param name="name" select="'format'"/>
        &lt;/xsl:call-template>
      &lt;/xsl:otherwise>
    &lt;/xsl:choose>
  &lt;/xsl:variable>
  &lt;xsl:choose>
    &lt;xsl:when test="normalize-space(.) = ''  and not($pi)">
      &lt;xsl:call-template name="datetime.format">
        &lt;xsl:with-param name="date" select="$date"/>
        &lt;xsl:with-param name="format">
          &lt;xsl:choose>
            &lt;xsl:when test="$pi">
              &lt;xsl:value-of select="$format"/>
            &lt;/xsl:when>
            &lt;xsl:otherwise>B d, Y&lt;/xsl:otherwise>
          &lt;/xsl:choose>
        &lt;/xsl:with-param>
        &lt;xsl:with-param name="padding" select="1"/>
      &lt;/xsl:call-template>
    &lt;/xsl:when>
    &lt;xsl:otherwise>
      &lt;xsl:apply-templates mode="book.titlepage.recto"/>
    &lt;/xsl:otherwise>
  &lt;/xsl:choose>
  &lt;/xsl:template>
  </pre>
- Flyer FO: is already corrected
- Pocket FO: open file suse/xslt/pocket/fo/booktitlepage.xsl, goto line 104 (should be a template that matches bookinfo/date). 
  Leave the fo:block intact, but delete the xsl:apply-templates line. Copy the _content_ of the above template into this template.

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-12-03 09:21**
- **labels**:  --> doc

**Comment by fsundermeyer** [comment]
No longer relevant, INVALID
