### ISSUE TITLE
Collecting Information about DocBook 5 [sf#155]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#155]
**Reported by tom_schr on 2013-05-28 13:05 UTC**
This ticket just collects some information about a migration of our sources and toolchain to DocBook 5.
# Overview

DocBook 5.x is the successor of DocBook 4. Any future changes will be integrated into version 5, the former is in maintenance mode.
## Changes

There are some changes between DocBook 4 and DocBook 5. Although they are not really difficult, it's important to know. Here are the major changes:
- DocBook 5 namespace
  All DocBook elements are now bound to a namespace, <tt>http://docbook.org/ns/docbook</tt>
- IDs
  Replace the attribute <tt>id</tt> with <tt>xml:id</tt>
- ulink renamed
  Use <tt>&lt;link&gt;</tt> instead
- Consolidated *info elements
- Assembly files (a kind of topic oriented approach), see Ticket [#164]

Find more changes at http://docbook.org/tdg51/en/html/ch01.html#introduction-whats-new and http://docbook.org/docs/howto/#changes.
## Benefits
- Flexibility: We can better change the DocBook 5 schema (it's easier to adapt RELAX NG than DTD)
- New stylesheets will be (probably) support DocBook 5 
- Migration is relatively easy, there is a stylesheet that converts version 4 into version 5, see http://doccookbook.sf.net/html/en/dbc.structure.db4-to-db5.html
- We can get rid of Novdoc ;)
- It's the future ;)
# Current Situation
## DAPS

Currently, DAPS supports validation of DocBook 5 files with jing already.
## DTD, Schema

We need to create a special version of Novdoc for DocBook 5; see also Ticket [#180]. The primary schema language is RELAX NG (probably the compact version). DTD is derived from the RNC version.
## Stylesheets

The current customization doesn't recognize the DocBook 5 namespace.
# Migration

Use the stylesheet https://docbook.svn.sourceforge.net/svnroot/docbook/trunk/docbook/relaxng/tools/db4-upgrade.xsl to upgrade your DocBook 4 document.

**Comment by tomschr** [comment]
**Commented by tom_schr on 2015-02-10 10:12**
Meanwhile, we have some migration stylesheets in `daps/daps-xslt/migrate/`.

**Comment by tomschr** [comment]
This issue was moved to openSUSE/suse-xsl#13

**Comment by tomschr** [comment]
Reopened as it is just copied to openSUSE/suse-xsl

**Comment by fsundermeyer** [comment]
Closing - we successfully moved to DocBook5
