### ISSUE TITLE
Replace DEF Files [sf#170]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#169]
**Reported by tom_schr on 2013-07-23 11:39 UTC**
Currently, when generating HTML on docserv, linking from one book into another is broken (as docserv contains subdirectories).

We need some way to tell daps (and the XSLT stylesheets) which book should go into which directories (correcting also the links).

Keep in mind, we need this for single and chunked HTML.

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2013-11-07 10:55**
In addition to that we should add a --local_links switch that takes care of replacing links to other books with a text only version (same is done with bigfile).

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-12-03 09:19**
- **labels**: xslt, daps --> xslt, daps, doc

**Comment by tomschr** [comment]
**Commented by tom_schr on 2013-12-03 09:19**
Something for a possible DAPS developer guide?

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2014-10-24 09:41**
- **Milestone**: 2.0 --> Future

**Comment by fsundermeyer** [comment]
No longer required, WONTFIX
