### ISSUE TITLE
Documentation: Create flow chars [sf#17]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#17]
**Reported by tom_schr on 2011-12-16 12:51 UTC**
Create flow charts of Makefile mechanic [2011-04-06, fs] and include it into the documentation (see [ticket#1]).

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2012-01-24 13:10**
- **status**: open --> needinfo
- **assigned_to**: Tanja Roth

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2012-01-24 13:10**
Not sure if this is really need - Tanja please decide if you want to have such things in the documentation or not... .

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2012-01-31 08:16**
- **summary**: Create flow chars --> Documentation: Create flow chars

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2012-01-31 08:30**
- **info_provider**: Tanja Roth

**Comment by tomschr** [comment]
**Commented by taroth21 on 2012-02-01 12:47**
Would rather not include them in a User's Guide. However, flow charts of the makefile mechanism  would be useful for a Developer's Guide. Therefore leaving the ticket open.  

- **status**: needinfo --> open

**Comment by tomschr** [comment]
**Updated by taroth21 on 2012-02-07 15:16**
- **milestone**: 1.0 --> Future


- **info_provider**: Tanja Roth -->  nobody

**Comment by taroth21** [comment]
Closing as works for me.
