### ISSUE TITLE
/etc/daps/config.in should not be packaged [sf#177]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#176]
**Reported by fsundermeyer on 2013-09-16 07:59 UTC**
The RPM package contains the file /etc/daps/config.in. It should not be part of the package.

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2013-09-16 08:19**
Looks like the following line from Makefile.am is not ptoperly processed/ignored:

nodist_dapsconf_DATA  = etc/config.in etc/catalog.xml

**Comment by fsundermeyer** [comment]
The nodist parameter only excludes files when creating a source tarball it seems. Solved this issue by excluding the file via spec-file (see commit 7be6b127a).
