### ISSUE TITLE
Embedding PDFs as images seems to only give error messages with FOP [sf#179]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#178]
**Reported by sknorr on 2013-09-27 14:35 UTC**
When trying to embed PDF files as images into PDF output, FOP seems to be struggling. Building doesn't fail, but I get error messages about the PDFs and it seems like the PDFs aren't embedded into the file either.
See, e.g. the DAPS test docs in trunk/test/docs .

(Same is true of EPS files, of course.)

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2013-09-27 14:41**
- **status**: open --> needinfo
- **Info Provider**: Stefan Knorr --> Thomas Schraitle

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2013-09-27 14:41**
I know - this does not work with FOP because it lacks support for it.

toms, are you aware of any news on this matter?

**Comment by tomschr** [comment]
**Commented by sknorr on 2013-09-27 15:05**
Oh. Is that a duplicate then?

I am fairly sure Tom is unaware, since he asked me if Kilian hadn't written something to that end.

Hm, maybe we could make do temporarily by converting PDFs to something else?
- http://kate-editor.org/2013/06/01/how-to-convert-pdf-to-svg/
- http://www.cyberciti.biz/faq/howto-convert-a-pdf-file-to-an-image/

**Comment by tomschr** [comment]
**Commented by sknorr on 2013-12-18 15:23**
To add insult to injury, apparently DAPS 2 beta converts SVG images to PDF. And PDF still does not work with FOP. So, both formats utterly and completely fail to be included in the PDF output.

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2013-12-19 15:03**
Yes, SVGs are converted to PDF. But they are only embedded as PDFs if "requested" in the XML sources. Use
\<imagedata fileref="foo.svg"\>
and the image will be embedded as SVG.
This feature has been added because both FOP and XEP fail to embed SVG 1.1 images containing gradients (which is almost always the case). When embedding them as PDF it works at least with XEP.

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2013-12-19 15:04**
toms, I am still curious what happened to the PDF-support for FOP stuff Kilian had been working on.

**Comment by tomschr** [comment]
**Commented by tom_schr on 2014-02-04 14:02**
There is a thread from Kai Hofmann (2014-02-04T14:26) on the fop mailinglist. This could be interesting for us:

http://mail-archives.apache.org/mod_mbox/xmlgraphics-fop-users/201402.mbox/browser

Summary:
- Use FOP trunk
- FOP trunk includes a patched fontbox-1.8.3 
- New FOP releases with patched fontbox/pdfbox are expected to be published soon

**Comment by ghost** [comment]
DAPS no longer supports PDF/EPS files as an image format since v3.1. This issue is moot.
