### ISSUE TITLE
Update DAPS homepage [sf#182]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#181]
**Reported by sknorr on 2013-10-02 12:46 UTC**
It might be good to update the daps.sf.net homepage (and the documentation linked from there) to the new layout.
The documentation should be simple to regenerate, I would volunteer to re-do the homepage in a matching style.

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2013-12-19 14:05**
- **assigned_to**: Frank Sundermeyer --> Stefan Knorr
- **Info Provider**: Stefan Knorr --> Frank Sundermeyer

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2013-12-19 14:05**
Please go ahead with re-doing the Home page - that would be very much appreciated.
I'd like to release the updated homepage together with the DAPS 2.0 release.
The homepage files are located in SVN at trunk/daps/project-web/

I will take care of updating the manuals upon release time.

**Comment by tomschr** [comment]
Is related to issue #259

**Comment by mschnitzer** [comment]
done by:
https://github.com/openSUSE/daps/commit/2fbdc0fba83b3455a89b7f6def55707b073c03f5
https://github.com/openSUSE/daps/commit/7dca5c2d91142cfbec66a440b9358559eaf5e255
https://github.com/openSUSE/daps/commit/fe8b411c249d3bd479ea2a28bd29a0b96184899c
https://github.com/openSUSE/daps/commit/a1b48dfa9593401459db2ff731913b327f047497
