### ISSUE TITLE
Make use of saxon6-batch (if existing) [sf#187]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#186]
**Reported by fsundermeyer on 2013-10-22 11:40 UTC**

```
saxon6-batch -batch batch.csv -style foo.xsl param=value
```

batch.csv:

```
INPUT;OUTPUT
```

Alternative ??

```
saxon6-batch -batch batch.csv param=value
```

batch.csv:

```
INPUT;OUTPUT;XSL-STYLESHEET
```

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-12-02 14:47**
- **labels**:  --> saxon

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-12-03 09:12**
- **labels**: saxon --> saxon, doc

**Comment by tomschr** [comment]
**Commented by tom_schr on 2013-12-03 09:12**
Probably something for a possible DAPS developer guide

**Comment by ghost** [comment]
Fairly sure this is irrelevant now. Closed.
