### ISSUE TITLE
HTML: Hyphenation of Product Names [sf#190]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#189]
**Reported by taroth21 on 2013-10-25 13:49 UTC**
Seems the hyphenation of product names does not work as expected in HTML: I just stumbled across the following hyphenation for "OpenStack" in the HTML output: "OpenS-tack". Is it possible to pass hyphenation patterns for product names?

**Comment by tomschr** [comment]
**Commented by tom_schr on 2013-10-25 15:26**
I fear, this is a Firefox bug.

See also Ticket[#33]. We could use special "markers" to help the hyphenation algorithm.

Here is a list of these marker which we could try (all hexadecimal values):
- U+00AD SOFT HYPHEN
- U+200B ZERO WIDTH SPACE
- U+2011 NON-BREAKING HYPHEN
- U+2027 HYPHENATION POINT
- U+2060 WORD JOINER
- U+FEFF ZERO WIDTH NO-BREAK SPACE

Use the following notation to include the above character in your XML:

```
&#xUNICODE;
```

For additional information, maybe the article about [Unicode Line Breaking Algorithm](http://www.unicode.org/reports/tr14/) contains some useful information. Especially [Table 1](http://www.unicode.org/reports/tr14/#Table1) contains a list of breaking codes.

The Wikipedia article contains detailed information about the line breaking algorithm (German only): https://de.wikipedia.org/wiki/Unicode-Zeilenumbruch-Algorithmus

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-12-03 09:09**
- **labels**:  --> doc

**Comment by tomschr** [comment]
**Commented by tom_schr on 2013-12-03 09:12**
If we know all the details, the information herein could lead to a informative section about how to influence linebreak: how to avoid and how to break.

**Comment by fsundermeyer** [comment]
Does not look like this is an issue any longer. Closing as WONTFIX
