### ISSUE TITLE
Profiling adds whitespace to screens [sf#193]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#192]
**Reported by sknorr on 2013-11-12 16:45 UTC**
It seems, DAPS now adds copious amounts of whitespace to certain screens.

E.g. in the SUSE cloud admin guide (File: xml/admin_dashboard.xml +1117), we have this humble screen:

```
<screen><replaceable>DESTINATION_CIDR</replaceable>,<replaceable>NEXTHOP</replaceable></screen>
```

<br/>

Which is turned into this after profiling (File: build/.profiled/p_sles/admin_dashboard.xml +2760)*:

```
<screen>
                     <replaceable>DESTINATION_CIDR</replaceable>,<replaceable>NEXTHOP</replaceable>
</screen>
```

<br/><br/>
- Note the difference in line numbers!

**Comment by tomschr** [comment]
**Commented by sknorr on 2013-11-12 16:46**
- Description has changed:

Diff:

```

--- old
+++ new
@@ -6,8 +6,10 @@

 <br/>

-Which is turned into this after profiling (File: build/.profiled/p_sles/admin_dashboard.xml +1117):
+Which is turned into this after profiling (File: build/.profiled/p_sles/admin_dashboard.xml +2760)*:

     <screen>
                          <replaceable>DESTINATION_CIDR</replaceable>,<replaceable>NEXTHOP</replaceable>
     </screen>
+<br/><br/>
+* Note the difference in line numbers!

```

**Comment by tomschr** [comment]
**Commented by tom_schr on 2013-11-12 18:04**
Short notice: Couldn't reproduce it with daps 1.1.7 (although I've added the above screen element).

**Comment by tomschr** [comment]
**Commented by sknorr on 2013-11-13 09:31**
This is Saxon's fault somehow, which when profiling with DAPS profiling stylesheets from trunk/daps-xslt/profiling/ produces generally rather wacky indentations.

**Comment by tomschr** [comment]
**Commented by taroth21 on 2013-11-27 16:31**
Bad news: Now it happened to me, too - even without using Saxon. So looks like it is not Saxon's fault after all. ;)
I built the DAPS Quick Start from trunk (once with XEP and once with FOP) and some screens were indented to the middle of the page, others were OK. The source code for all of them looks OK, as does the profiled file (Stefan confirmed that it is not similar to the examples he had seen before).

**Comment by tomschr** [comment]
**Updated by tom_schr on 2015-02-10 10:09**
- **labels**:  --> profiling, xslt, saxon

**Comment by tomschr** [comment]
This issue was moved to openSUSE/suse-xsl#19

**Comment by ghost** [comment]
This is indeed a DAPS issue. Not reopening, because we cannot reliably reproduce this anywhere.
