### ISSUE TITLE
Implement subcommand to find filename for an ID [sf#194]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#193]
**Reported by tom_schr on 2013-11-13 14:31 UTC**
Revision [r3811] implemented the "new" (now correct) behaviour of getting a filelist.

This method could be used to have it separated into a subcommand. For example, the user knows an ID and want to have the respective filename where it belongs. For example, the syntax could be:

```
daps -D DC-foo filename --rootid=XYZ
```

the output is the filename.

**Comment by tomschr** [comment]
**Commented by tom_schr on 2013-12-02 13:45**
Fixed in [r3873]. 
You need to set the parameter "show.first" to 1 to show only the first filename.

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-12-02 13:45**
- **status**: open --> needinfo

**Comment by tomschr** [comment]
**Commented by tom_schr on 2013-12-02 13:45**
If everything works, please assign to Tanja.

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-12-03 09:07**
- **labels**: daps --> daps, doc

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2013-12-03 11:45**
- **status**: needinfo --> closed
- **Info Provider**: Thomas Schraitle -->  nobody

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2013-12-03 11:45**
Added new subcommand list-file with SVN revision [r3877].

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2013-12-03 11:47**
- **status**: closed --> pending
- **assigned_to**: Frank Sundermeyer --> Tanja Roth

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2013-12-03 11:47**
Re-Assigning for documentation

**Comment by taroth21** [comment]
It has been implemented as
`daps -D DC-foo list-file --rootid=XYZ`
and is already documented in the DAPS User Guide since quite a while, see http://opensuse.github.io/daps/doc/cha.daps.user.edit.html#sec.daps.user.edit.manage, Checking Where an ID or File is Included
