### ISSUE TITLE
DAPS now only prints name of HTML directory [sf#197]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#196]
**Reported by sknorr on 2013-11-20 17:14 UTC**
When doing

```
{daps from repo} -d DC-something html
```

, the output at the end just displays the path of the output files, without the final index.html appended. Since browsers are not clever enough to find that file on their own, this means, I have to append the index.html part myself.

Could this be re-enabled?

**Comment by tomschr** [comment]
**Updated by sknorr on 2013-11-27 13:48**
- **summary**: DAPS pnly prints name of HTML directory now --> DAPS now only prints name of HTML directory

**Comment by tomschr** [comment]
**Commented by sknorr on 2013-11-27 16:13**
Tanja told me that this change was done for the sake of being able to more easily run test cases. Which is nice, but unfortunately test cases != users. And while both are important, test cases only make sense if we have users.

Also, Karl would like to forbid you from making such changes in the future. ;)

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2013-12-19 12:38**
This change was introduced for consistency - whenever daps produces a multiple file output, the result message points to a directory rather than to one selected file from the directory. I considered the fact that this was not done on HTML builds a bug and thus fixed it.

BTW: Browsers have been  displaying the context of index.html or index.htm by default in the past. If they do not do this anymore, it's probably a matter of setting a configuration option in the browser.

**Comment by tomschr** [comment]
**Commented by sknorr on 2014-01-07 10:24**
re comment #3:

> Browsers have been displaying the context of index.html or index.htm by
> default in the past.

I think that is a (common) server-side setting only (and therefore doesn't apply to locally-viewed files). As far as I know, you could just as well configure your server to give clients a "not authorised" message or a file overview page.

Also, I know this used to be inconsistent, but the new behaviour really breaks my usage of DAPS to a degree...

**Comment by fsundermeyer** [comment]
Wontfix for reasons mentioned above
