### ISSUE TITLE
Create DAPS Developer Guide [sf#204]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#203]
**Reported by tom_schr on 2013-12-03 11:50 UTC**
To collect all ideas which goes beyond simple user interaction, we need a DAPS Developer Guide.

The topics could be:
- How to integrate your own stylesheets in DAPS
- How to change stylesheets
- Anything else that matters ;)

See also some https://sourceforge.net/p/daps/tickets/search?q=labels:doc

**Comment by fsundermeyer** [comment]
No resources, WONTFIX
