### ISSUE TITLE
Implement SVG cleaner to get semi-correct output in PDFs with FOP [sf#213]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#212]
**Reported by sknorr on 2013-12-18 15:28 UTC**
We need some way to reliably get SVGs into DAPS-created PDFs.

Converting SVGs to PDFs first and then embedding those PDFs into the final output PDFs is clearly not an option. We Should find a way to convert SVGs to a maximally compatible subset of tags.
- Remove special Inkscape tags
- Replace FlowRoot with Text
- Maybe even replace gradients (or at least use a simpler method to re-create them, as Inkscape uses some sort of intra-document links for this sort of thing which quite likely not every application understands)

**Comment by tomschr** [comment]
**Commented by tom_schr on 2013-12-18 15:40**
Well, Inkscape "tags" (actually they are either CSS properties or XML attributes) are really, really annoying: they start with "-" which is not allowed in XML.

I've thought of a cleanup solution in the past, but came up as really challenging. We have a very simple XSLT stylesheet (<tt>daps-xslt/common/svg2svg.xsl</tt>) which replaces the annoying style attribute with the corresponding attributes. This makes modifying SVGs a lot easier. It doesn't solve the problem, I know.

I doubt it is possible of replacing <tt>svg:flowRoot</tt> with XSLT. You need information about the font (it's width, height, etc.), the text inside that flow, and where you break them. Not possible with XSLT without any extension function.

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-12-18 15:41**
- **status**: open --> needinfo
- **Priority**: high --> low

**Comment by tomschr** [comment]
**Commented by tom_schr on 2013-12-18 15:41**
I'll change the status to "needinfo". If we know how to do it, it may be possible.

**Comment by tomschr** [comment]
This issue was moved to openSUSE/suse-xsl#24

**Comment by ghost** [comment]
Moving this back. This has nothing to do with the output stylesheets.

**Comment by ghost** [comment]
_[copied comment from the suse-xsl issue.]_

One software we could look at is SVGO. Ultimately, it is not really an option itself, more of a potential source of inspiration.

Problems with it include:
- SVGO's focus is rather different: it focuses on shaving off bytes, so they can be transferred faster over the internet
- Written in JS for Node, so: 
  - We'd have a Node dependency in DAPS.
  - There is also the issue that Node uses its own package manager, `npm`. While Node and `npm` itself are included in the OpenSUSE repos, no other Node module is. (This means that the DAPS package could require `npm` and on the first invocation would have to run `npm install svgo` or so.)

**Comment by tomschr** [comment]
I don't like the idea to have a Node requirements in daps.

Well, the problem is still unresolved, but I don't think the situation is as bad as it may look: most SVGs are illustrations and when there was a problem, I fixed it manually.

I had issues mostly with the `flowText` element, but that depends on the tools you use. Careful creation avoids it.

"Wrong" attributes are solved by the mentioned stylesheets. For the time being, I don't see any better improvement than fixing it manually.

As there aren't many SVGs to fix and it is not a big task, I close it for the time being.
