### ISSUE TITLE
Recursion in suse2005 HTML stylesheets [sf#214]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#213]
**Reported by fsundermeyer on 2013-12-20 11:23 UTC**
[r3760] introduced a template recursion to the HTML templates that caused HTML builds to fail. [r3962], [r3963], and [r3964] provided a hotfix, but this needs to be looked into again.

**Comment by tomschr** [comment]
**Commented by tom_schr on 2013-12-20 11:40**
- Description has changed:

Diff:

~~~~

--- old
+++ new
@@ -1 +1 @@
-[r3760] introduced a template recursion to the HTML templates that caused HTML builds to fail. [r3962] and [r3963] provided a hotfix, but this needs to be looked into again.
+[r3760] introduced a template recursion to the HTML templates that caused HTML builds to fail. [r3962], [r3963], and [r3964] provided a hotfix, but this needs to be looked into again.

~~~~

**Comment by ghost** [comment]
This is a stylesheet issue. Closed.
