### ISSUE TITLE
Investigate New Catalog Schema [sf#219]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#218]
**Reported by tom_schr on 2014-03-14 12:09 UTC**
# Current Situation

Our catalog system looks like this:

```
/etc/xml
+-- catalog   # Main catalog file
|
+-- suse-catalog.xml
|
+-- for-catalog-*.xml
```

The file `for-catalog*.xml` is mostly obsolete and are used to include a code snippet into the spec file.
# Additional Information
- https://github.com/openSUSE/xml-group-manager
- Debian XML Policy (Working Draft)
  http://debian-xml-sgml.alioth.debian.org/xml-policy/

**Comment by fsundermeyer** [comment]
This is no DAPS bug, moved to the SUSE bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=978008
