### ISSUE TITLE
Try adding 0-width spaces within commands etc. to FOP input [sf#223]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#222]
**Reported by sknorr on 2014-03-24 12:06 UTC**
FOP is currently set to hyphenate commands/filenames/URLs/etc. That usually makes it impossible to trust these elements as being shown in the way they need to be entered.

A previous trial of adding zero-width spaces and disabling hyphenation has failed (according to Tom), but it may be time to try again.

**Comment by ghost** [comment]
This is not a DAPS issue. toms has created https://github.com/openSUSE/suse-xsl/pull/348 for this.
