### ISSUE TITLE
Let stylesheets know which version of DAPS calls them [sf#227]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#226]
**Reported by sknorr on 2014-06-30 13:01 UTC**
The current suse2013 stylesheets (try to) use the DAPS version number, e.g. for setting the PDF property Creator to "DAPS V2.0 (http://daps.sf.net) with DocBook V1.77.1" etc.
(This is currently not used in the HTML version of the stylesheets, but could be in the future.)

This functionality is useful for all manner of things from bug reporting to advertising DAPS/DocBook. However, it would be great if the information were accurate, too.

Currently, the FO stylesheets hardcode the name "DAPS" and the version number is the version of suse-xsl-stylesheets package. That seems rather unfortunate, since the stylesheet version and the DAPS version are generally not completely aligned, and it might also be the case that someone uses an older DAPS version with newer stylesheets or vice versa. Thus, I would propose adding two parameters to every xsltproc/Saxon call from DAPS:

```
$CREATOR.NAME=e.g. DAPS
$CREATOR.VERSION=e.g. 2.0
```

The stylesheets could then use these accurate values. Profit!

**Comment by fsundermeyer** [comment]
Fixed with commit c156c4b

The string parameters 
- converter.name
- converter.version

will be set for ePUB, HTML, PDF and man page builds.
