### ISSUE TITLE
DAPS apparently has problems with : (colons) in directory names [sf#232]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#231]
**Reported by sknorr on 2014-08-06 12:34 UTC**
I tried building from a DC file which was located under this path:

```
/home/user/oscar/home:user:branches:SUSE:SLE-11-SP3:GA/SLES-admin_de_src_set/DC-SLES-admin
```

This did not work and turned up:

```
/usr/share/daps/make/selector.mk:36: *** target pattern contains no `%'.  Stop.
```

I moved a directory further up, like so:

```
/home/user/oscar/SLES-admin_de_src_set/DC-SLES-admin
```

This then did work. Ergo: colons must be the problem..?

(Btw, that the book came from a package within the build service was incidental, I was not looking to build the whole package, just the book itself. So, no, you will not happen upon this error during the usual package build, thus only setting priority to medium.)

**Comment by tomschr** [comment]
**Commented by sknorr on 2014-08-06 12:35**
- Description has changed:

Diff:

~~~~

--- old
+++ new
@@ -2,7 +2,9 @@
 
     /home/user/oscar/home:user:branches:SUSE:SLE-11-SP3:GA/SLES-admin_de_src_set/DC-SLES-admin
 
-This did not work.
+This did not work and turned up:
+
+    /usr/share/daps/make/selector.mk:36: *** target pattern contains no `%'.  Stop.
 
 I moved a directory further up, like so:
 
@@ -10,4 +12,5 @@
 
 This then did work. Ergo: colons must be the problem..?
 
+
 (Btw, that the book came from a package within the build service was incidental, I was not looking to build the whole package, just the book itself. So, no, you will not happen upon this error during the usual package build, thus only setting priority to medium.)

~~~~

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2014-08-06 13:35**
Further readings:

https://stackoverflow.com/questions/2052406/escaping-colons-in-filenames-in-a-makefile

http://www.mail-archive.com/bug-make@gnu.org/msg03318.html

**Comment by fsundermeyer** [comment]
This is a GNU make restriction that cannot be solved. Wontfix.
