### ISSUE TITLE
Build manifest files for all file formats that fundamentally consist of multiple files [sf#233]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#232]
**Reported by sknorr on 2014-08-06 13:24 UTC**
All manner of HTML formats (including EPUB/Mobipocket) necessitate the copying of secondary files (that is, CSS, images, fonts, javascript). Currently, DAPS cannot always be sure to copy the correct/actually necessary files.

Therefore, DAPS should build a manifest file from the generated files before copying secondary files into the folder that contains the generated files.
##### The process would thus become:
1. User starts `daps`
2. DAPS generates the content files via XSLT
3. [NEW!] DAPS scans within the content files:
   1. within the content files itself: for tags like `<link\>`, `<script\>`, `<img\>`, `<video\>`, `<audio\>`, `<style\>` (possibly non-exhaustive) that reference other files
   2. DAPS assumes that all referenced files whose do not start with a prefix like `http://` or `https://` are located within `$STYLEROOT` and adds these to the list of files to copy
   3. Some file types (CSS, SVG, JS) may contain further references. In as far as possible, will try to search these files for those references and also add these to the list.
4. Copy files that are listed in the manifest
5. PROFIT!
##### Searching things...
- _basic HTML tags_: is probably not too hard, but tricky enough, the software would need to correctly discern HTML tags from the text, but then support for the elements `link` (`@href`), `img` (`@src`), `video` (`@src`), `audio` (`@src`) would be relatively simple. 
  - the `style` element is a bit trickier, but boils down to searching through CSS (see CSS section below)
  - the `script` tag can probably be assumed to be unparseable (see JS section below)
  - `src` or `href` attributes can contain a base64 string (needs to be excluded)
- _CSS_: look for `url(` and use everything that stands between that and before the closing `)`. Possible issues (need to be excluded):
  - `url(` can be followed by a base64 string
  - a selector like `a::before {content: 'url(something)'}` could theoretically appear
- _JS_: assume these files to be unparseable without executing them, as Javascript contains more than enough string functions too shoot us in the feet. There are three possible conventions to circumvent this problem that I can think of and those are:
  - never reference anything from Javascript (this is easy with images, but harder to when wanting to reference other JS files)
  - never construct file names in Javascript, always write out the full string
  - add some manifest to the start of the JS file itself, keeping track of everything the file references
- _SVG_: mostly simple, look for items in the `xlink` namespace. However, SVG can also contain Javascript, so ymmv (see above).
- _Files that need not be searched for further references:_ JPG, PNG, GIF, OTF, TTF, EOT, WOFF etc.

**Comment by tomschr** [comment]
**Commented by sknorr on 2014-08-06 13:29**
- Description has changed:

Diff:

~~~~

--- old
+++ new
@@ -13,9 +13,10 @@
 
 ##### Searching things...
 
-* *basic HTML tags*: is probably not too hard, but tricky enough, the software would need to correctly discern HTML tags from the text, and support for the elements `link` (`@href`), `img` (`@src`), `video` (`@src`), `audio` (`@src`) would be relatively simple. 
+* *basic HTML tags*: is probably not too hard, but tricky enough, the software would need to correctly discern HTML tags from the text, but then support for the elements `link` (`@href`), `img` (`@src`), `video` (`@src`), `audio` (`@src`) would be relatively simple. 
     * the `style` element is a bit trickier, but boils down to searching through CSS (see CSS section below)
     * the `script` tag can probably be assumed to be unparseable (see JS section below)
+    * `src` or `href` attributes can contain a base64 string (needs to be excluded)
 * *CSS*: look for `url(` and use everything that stands between that and before the closing `)`. Possible issues (need to be excluded):
     * `url(` can be followed by a base64 string
     * a selector like `a::before {content: 'url(something)'}` could theoretically appear
@@ -24,3 +25,5 @@
     * never construct file names in Javascript, always write out the full string
     * add some manifest to the start of the JS file itself, keeping track of everything the file references
 * *SVG*: mostly simple, look for items in the `xlink` namespace. However, SVG can also contain Javascript, so ymmv (see above).
+
+* *Files that need not be searched for further references:* JPG, PNG, GIF, OTF, TTF, EOT, WOFF etc.

~~~~

**Comment by tomschr** [comment]
**Commented by sknorr on 2014-08-06 13:46**
- Description has changed:

Diff:

~~~~

--- old
+++ new
@@ -7,9 +7,11 @@
 1. User starts `daps`
 2. DAPS generates the content files via XSLT
 3. [NEW!] DAPS scans within the content files:
-3.1. within the content files itself: for tags like `<link\>`, `<script\>`, `<img\>`, `<video\>`, `<audio\>`, `<style\>` (possibly non-exhaustive) that reference other files
-3.2. DAPS assumes that all referenced files whose do not start with a prefix like `http://` or `https://` are located within `$STYLEROOT` and adds these to the list of files to copy
-3.3. Some file types (CSS, SVG, JS) may contain further references. In as far as possible, will try to search these files for those references and also add these to the list.
+    1. within the content files itself: for tags like `<link\>`, `<script\>`, `<img\>`, `<video\>`, `<audio\>`, `<style\>` (possibly non-exhaustive) that reference other files
+    2. DAPS assumes that all referenced files whose do not start with a prefix like `http://` or `https://` are located within `$STYLEROOT` and adds these to the list of files to copy
+    3. Some file types (CSS, SVG, JS) may contain further references. In as far as possible, will try to search these files for those references and also add these to the list.
+4. Copy files that are listed in the manifest
+5. PROFIT!
 
 ##### Searching things...
 

~~~~

**Comment by fsundermeyer** [comment]
There is no reports of missing files when generating packages, so I do not see a usecase for the requested manifest files. Closing as WONTFIX.
