### ISSUE TITLE
Ship modified fonts TomsCallouts & Nimbus with the stylesheets package instead of with the DAPS package [sf#235]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#234]
**Reported by sknorr on 2014-08-14 13:36 UTC**
Logically, these fonts belong into the xslt2005 package and the only thing could hold us up here is probably the XEP configuration file that sets up paths to all fonts XEP is supposed to use. But, iirc, that is already shipped with the stylesheets.

**Comment by fsundermeyer** [comment]
Moved the font installation to the suse-xsl-stylesheet package.
