### ISSUE TITLE
Verifying SVG files [sf#237]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#236]
**Reported by keichwa on 2014-08-19 14:58 UTC**
It would be nice, if daps would also verify SVG files.  For example, fop still does not support the flowRoot element and it would be very helpful if daps would warn at least.

**Comment by tomschr** [comment]
**Commented by sknorr on 2014-08-19 15:41**
Another SVG feature DAPS could warn against:

Incompatible gradients

> **NOTE:** This needs testing! Some gradients definitely
> do work reliably.
> _Theory 1:_ it may just be the fact
> that Inkscape usually generates a structure like this for gradients:

```
    <defs>
      <linearGradient> [...] </linearGradient>
    </defs>
    [...]
    <rect style="fill:url(#linearGradient2993)"/>
```

> That is, putting the gradient into the main CSS might already help. I have
> not yet tested this, though.
> _Theory 2:_ It may have to do with the fact that our PDF
> output profile does not support transparency, thus
> gradients that use transparency might lead to errors.

**Comment by tomschr** [comment]
That would require the `svg-schema` package. With the help of this package, it would be possible to validate our SVG files against the DTD/schema.

**Comment by fsundermeyer** [comment]
We do nate have a clear picture when and why inkscape fails on certain SVGs, so I'd rather not implement this.
