### ISSUE TITLE
Make installing Saxon 6 support easier [sf#238]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#237]
**Reported by sknorr on 2014-08-19 16:28 UTC**
Saxon is currently not a dependency of DAPS, but since DAPS does not work with just vanilla Saxon 6 installed, it is currently necessary to install a half dozen extra packages:

```
    saxon6 saxon6-scripts xerces-j2 xerces-j2-xml-resolver xerces-j2-xml-apis
    xml-commons-jaxp-1.3-apis xml-commons-resolver12 *
```

_(\_Note that I am not entirely sure which of these are dependencies of each other and which genuinely need to be installed. But I know that more than three of these need to be individually installed in addition to Saxon itself.)*

The other problem is that while DAPS creates a nice error message when the saxon6 package itself is not installed, it will happily let Saxon run, even if the dependent packages are not installed. Saxon then, of course gives out less nice messages. _(Note that DAPS itself specifically instructs Saxon to use the extra packages that are not normally installed, so this is not Saxon's or the Saxon package's fault.)_

**There are multiple ways to resolve this issue:**
1. Add saxon6 and all the necessary packages to make it run under DAPS as requires/recommends to the DAPS package (very simple, but would always pull in even more extra packages)
2. Create a package `daps-saxon6-support` that contains either:
   
   2.1 "requires" for `saxon6` and all its related packages, DAPS itself could then check with `rpm` whether the support package is installed (relatively simple, but creates dependency on RPM [= not portable, slow])
   2.2 "requires" for `saxon6` and all its related packages and a small file that DAPS could check with whether Saxon 6 support is installed (relatively simple, not as clean)
   2.3 "requires" for `saxon6` and all its related packages and an add-on script/make file that contains all the Saxon-related logic (clean, opens up the possibility for future expansion, e.g. Saxon 9, Xalan...)

**Comment by fsundermeyer** [comment]
Superseeded by #702
