### ISSUE TITLE
`daps locdrop` is apparently SVN-dependant [sf#239]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#238]
**Reported by sknorr on 2014-08-20 15:10 UTC**
Using `daps -d DC-[something] locdrop` outside of an SVN repository leads to:

```
    /usr/share/daps/make/packaging.mk:319: *** Fatal error: Cannot get
    list of translated files because /home/usr/dir/xml/file.xml is not SVN
    controlled.  Stop.
```

This would potentially block moving to another VCS, such as Git.

**Comment by fsundermeyer** [comment]
Fixed with commit daa205678549ef0667bec4ebd83f62b2208609b4
