### ISSUE TITLE
Make EPUB3 Default [sf#245]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#244]
**Reported by tom_schr on 2014-10-30 09:55 UTC**
When building EPUB, version 2 is created by default. You can switch to EPUB3 by using the `--epub3` option.

As the EPUB2 stylesheets are, well, not very customizable, we should consider to switch to EPUB3 by default. Maybe we should rename the `--epub3` option to `--epub2` and still offer EPUB2 generation. In case, someone really needs it.

**Comment by tomschr** [comment]
**Updated by tom_schr on 2014-10-30 09:58**
- **Milestone**: 3.0 --> 2.x

**Comment by fsundermeyer** [comment]
A switch to epub3 by default requires properly working SUSE stylesheets. As of Mar 2015, they need further polishment.
Re-assigning to tomschr.

**Comment by fsundermeyer** [comment]
Generating epub seems to be a feature seldomly used and making epub3 the default soes not seem to a a wanted/required feature.
Closing as wontfix, feel free to reopen if really needed.
