### ISSUE TITLE
Improve GitHub Pages

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#259]
At the moment, the lastest version of our HTML DAPS documentation is in the `gh-pages` branch. Some tasks should be completed:
1. Add a `robots.txt` file to help search engines.
2. Move the `index.html` page from SF to GH Pages and move all contents into a directory (for example, `doc/`). Link from the `index.html` to the documentation.
3. Update the DAPS documentation and adapt any version string.

**Comment by mschnitzer** [comment]
done by:
https://github.com/openSUSE/daps/commit/2fbdc0fba83b3455a89b7f6def55707b073c03f5
https://github.com/openSUSE/daps/commit/7dca5c2d91142cfbec66a440b9358559eaf5e255
https://github.com/openSUSE/daps/commit/fe8b411c249d3bd479ea2a28bd29a0b96184899c
https://github.com/openSUSE/daps/commit/a1b48dfa9593401459db2ff731913b327f047497
