### ISSUE TITLE
Cleanup DAPS Repo

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#260]
Some old leavings from the SVN to GH migration is still available:
- ~~`deprecated`: can be removed~~
- `contrib`: check, can be probably removed too
- ~~`devel`: check if it can be removed~~
- ~~`docmanager`: should go into a separate repository~~
- `logos`: should this be moved into the `gh-pages` branch?
- `project-web`: should go into the `gh-pages` branch; see also #259 
- ~~`suse`: most of them are available in the `suse-xsl` repository~~

**Comment by mschnitzer** [comment]
Done by: https://github.com/openSUSE/daps/commit/9d4f85f573ec922f5b9cec4d1d52421d558420e4
