### ISSUE TITLE
Investigate how to Connect GitHub with OBS

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#261]
Investigate how we can connect GitHub with openSUSE Build Server. The aim would be to create a new package whenever we create a new release. If possible, this should be done automatically (or with little hurdles).

Here are some links to start with:
- https://en.opensuse.org/openSUSE:Build_Service_Concept_SourceService
- https://github.com/openSUSE/xml-group-manager/settings/hooks/3031665

**Comment by tomschr** [comment]
@mschnitzer This is done for docmanager. The procedure there can be applied to daps as well. Please document your procedure, prefereably in the daps or docmanager wiki.

**Comment by fsundermeyer** [comment]
Fixed: https://build.opensuse.org/package/show/Documentation:Tools:Auto/daps
