### ISSUE TITLE
Make STYLEROOT Platform Independent

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#264]
Some of our files (mainly `Makefile.am` and `Makefile.in`) have this expression:

```
STYLEROOT    := $(DAPSROOT)/suse/xslt
```

whereas our `DC-*` files contain this line:

```
STYLEROOT="../suse/daps2013"
```

Neither the first nor the second path works. This is to be expected, as we moved the stylesheets to the `suse-xsl` repository and the `suse` directory is no longer available. Additionally, the expression is unfortunate as it won't build on our Travis CI server neither.

In order to make the path a little bit more platform neutral, I would suggest to integrate these lines:

```
X=$(xmlcatalog /etc/xml/catalog http://docbook.sourceforge.net/release/xsl/current/)
STYLEROOT=${X#file://*}
```

This would use the default DocBook XSL stylesheets (be it for the better or the worse).

However, we should consider the following issues:
1. The `daps2013` directory is only available in the `suse-xsl` repository. This means, the DAPS guides cannot be build without first cloning the repository.
2. Even if we clone it, the `daps2013` stylesheets depend on the `suse2013` stylesheets.

Needs to discuss this in person. ;-)

**Comment by fsundermeyer** [comment]
Fixed the issue by determining the correct stylesheet via configure. Thus the STYLEROOT configured in the DC-files and the one used in the Makefile are independent from each other.
