### ISSUE TITLE
DB4 -> DB5 migration stylesheet errors

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#273]
File: daps-xslt/migrate/suse-upgrade.xsl
- abstract are not correctly moved to the info element, but rather deleted; an info element is not created
  the only exception is a document where an <articleinfo> element exists <br/>
  NOTE: <Info> elements have to be created _before_ indexterm entries (in our DB4 documents,    indexterm entries appear before the abstract attribute
- Comments that exist before the start-tag are not migrated but rather deleted
- `<!CDATA[ ...]]>` is transferred to (valid) plain text:
  - old: `<![CDATA[<pool type='netfs'>]]>`
  - new: `&lt;pool type='netfs'&gt;`
- New line  in xref is transferred into spaces:
  
  ```
  <xref linkend="
  cha.add-ons"/>
  <xref linkend="    cha.add-ons"/>
  ```

**Comment by tomschr** [comment]
This is already fixed c5f6c4a
