### ISSUE TITLE
PROFILE_URN Detection Depends on Position of PI in Document

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#276]
`daps-xslt/common/get-xml-stylesheet.xsl` only returns the profiling URN if the PI is located _before_ the DOCTYPE definition. This is annoying and error prone.

**Comment by tomschr** [comment]
It seems, we get a different result depending on the XSLT processor:
- `saxon6` <br/>
  I get always a result, regardless of where the DOCTYPE definition is located.
- `xsltproc` <br/>
  Neither works.  :-1: 

Used versions:

```
$ rpm -q saxon6 libxslt-tools
saxon6-6.5.5-11.1.8.noarch, from Distribution: openSUSE 13.2
libxslt-tools-1.1.28-7.1.2.x86_64, from Distribution: openSUSE 13.2
```

**Comment by tomschr** [comment]
Additional hints:
With the previous commit, position of DOCTYPE isn't important anymore.
