### ISSUE TITLE
Support outputformat as Profiling Attribute

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#279]
### Current Situation

Since DocBook 5.1, there is a new `outputformat` attribute which can be used for profiling:
- `outputformat` <br>
  Indicates the output format (for example, print or epub) to which the element applies
### Issue

The `outputformat` is missing in DAPS as a common profiling attribute.
### Preferred Solution

It would be helpful to support this profiling attribute.

**Benefits**:

We can distinguish between different output formats, for example, print, epub, and online.
### More Information
- http://www.docbook.org/tdg51/en/html/ref-elements.html#common.effectivity.attributes
- https://sourceforge.net/p/docbook/rfes/296/ (original RFE from upstream)

**Comment by fsundermeyer** [comment]
Implemanted with commit 0ce2d82.

**Comment by tomschr** [comment]
Thanks! :+1:
