### ISSUE TITLE
Reorganize list of requirements and recommends

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#282]
When Karl tries to build books, recommended packages are not installed by default on OBS. This affects some important packages which are needed for DocBook  5 processing, mainly `docbook_5`, `docbook5-xsl-stylesheets`, and `jing`.

Should/could we switch the "Recommends" of these package into a "Requires" in the near future?

**Comment by fsundermeyer** [comment]
Fixed with commits 7dd994ff and 0d1b641.
