### ISSUE TITLE
Investigate better spell checking options

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#287]
Just having had the experience that my word list was rather not up to snuff, I got to discussing with toms about how to create a better spell checking experience.

I find the binary nature of the .rws file a bit of a hindrance to contributions (also, we could not find the source of the word list. Toms complained that for e.g. verbs, he always need to add all declensions separately.

As far as I know, Hunspell solves both of these issues. However, I am not sure if it is available as a command line executable or only as a library.

We also discussed if maybe Language Tool could be used for this, as we both knew that it had a Java GUI. However, it does a bit more (spelling + style) and we don't know much about how configurable it is. But it might serve as a workable UI for Hunspell.

**Comment by fsundermeyer** [comment]
As for adding words to the custom spellcheck directory, it is sufficient to add them to https://github.com/openSUSE/suse-xsl/blob/develop/aspell/suse_wordlist.txt

The .rws file is generated everytime a new package is released (or by running `make` in the checkout directory).

Apart from that I fully support looking for aspell alternatives. However, I fear that it is the only spellchecker that has proper XML support (AFAIK hunspell is lacking it).

**Comment by fsundermeyer** [comment]
Huinspell is supported since DAPS 3.0.0. Will become the default in DAPS 4.0.
