### ISSUE TITLE
When running daps spellcheck -v, use sdsc's new --module parameter

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#288]
suse-doc-style-checker 2014-02.2.99 now supports the parameter --module. This parameter creates some more output showing you which check module is currently being run.

Might be nice if DAPS supported it at some point in the future. Note that this is not yet shipped with a stable release and this bug is just for tracking.

[_Edith_: Note that the packaged 2014-02.2.99 version already contains this.]

**Comment by fsundermeyer** [comment]
Style checking will switch to vale (see #717), so there is no need to fix this issue.
