### ISSUE TITLE
Make generation of Bugtracker links in HTML configurable

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#290]
The SUSE stylesheets generate "Report Bug Links" for HTML by default.

It can be disabled by 
    param "use.tracker.meta to" 0

Would be nice to have a config variable or even a command line switch for this.

**Comment by ghost** [comment]
Isn't this something extremely stylesheet-specific? The tracker thingies only exist in SUSE2013, after all.

I see the point that it is not always helpful, e.g. when you are building locally in your home directory. However, I am not sure that a DAPS switch is the right approach here.

**Comment by fsundermeyer** [comment]
Stefan, you have a point. Closing as invalid.
