### ISSUE TITLE
DAPS Autobuild: Check whether individual DC files from <set/> need to be rebuilt

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#292]
(The following reflects the best of my understanding, but not necessarily reality. Feel free to amend.)

When there is a change in the repo that daps-autobuild pulls from, it will rebuild all books contained in the relevant set.

It would be cleverer, if it just rebuilt the books that actually changed within the set. (Or if that would be an option.)

**Comment by fsundermeyer** [comment]
mschnitzer is currently implementing a solution for this at https://github.com/mschnitzer/dapsenv
