### ISSUE TITLE
When given an SVG, DAPS tends to create a very large PNG for the HTML build from it

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#301]
E.g. take `{doc-sle repo}/images/src/svg/totem_pause_button.svg`:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16">
  <path d="m 4,4 0,8 3,0 0,-8 -3,0 z m 5,0 0,8 3,0 0,-8 -3,0 z"
    style="fill:#000000" />
</svg>
```

When building an HTML book from this, DAPS creates an 800x800 PNG from this SVG file, despite it clearly having `width` and `height` set to `16`.

**Comment by fsundermeyer** [comment]
Fixed with commit   7499990

The INK_OPTIONS variable contained the switch "-w 800" which makes inkscape export images with a fixed width of 800 ...
