### ISSUE TITLE
Enhancements in user guide

### ISSUE THREAD

**Issue by MartinKoeditz** [openSUSE/daps#315]
I think there a some typos in the user guide.
1. Examples 2.6 and 2.7 are (mostly) equal 
   I can't see the difference. Only differing elements are info and bookinfo. But I can't find a detailed description. If there are really some differences between both examples, please highlight the them.
2. Wrong switch in 4.4 Advanced Output Options
   Section "Getting More Information about the Building Process": The shown switch -debug2 in your example doesn't exist.

**Comment by tomschr** [comment]
@MartinKoeditz Thanks for the report!

You were absolutely right. I've fixed it with the above commit.

**Comment by tomschr** [comment]
I've also updated the `gh-pages` branch. The documentation on http://openSUSE.github.io/daps is now up-to-date for both HTML and PDF.
