### ISSUE TITLE
Add Changelog entry to Documentation?

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#317]
This is something for our DAPS documentation (probably very easy to fix).

I would suggest to add a link to the DAPS changelog https://github.com/openSUSE/daps/releases/latest. That way, the user can easily get information about the latest changes. Or, maybe, we could link to the [changelog](https://github.com/openSUSE/daps/blob/develop/ChangeLog) file itself.

**Comment by taroth21** [comment]
Just checked: the DAPS User Guide contains appendix C "What's new?" with a link to https://github.com/openSUSE/daps/blob/master/ChangeLog

But I can also change that and include the changelog file. @tomschr @fsundermeyer: Let's discuss the best option during hackweek.

**Comment by taroth21** [comment]
We agreed to keep the link to https://github.com/openSUSE/daps/releases/latest (as this contains all changes whereas https://github.com/openSUSE/daps/releases/latest only lists the most recent ones). Thus closing without any changes.
