### ISSUE TITLE
Catalog: missing noprofile entry

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#320]
After some restructuring, we now have two "noprofile" stylesheets:
- noprofile4.xsl: for DocBook4 contents
- noprofile5.xsl: for DocBook5 contents

These two entries are missing in our XML catalog file.

**Comment by fsundermeyer** [comment]
Contrary to the "real" profiling stylesheets, there is no need to resolve URNs for the noprofile stylesheets, so there is no need for catalog entries. Closing as invalid.
