### ISSUE TITLE
Enable SVG2Grayscale stylesheet to handle rgba(), hsl(), hsla(), hwb()

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#329]
These are CSS3 properties. They should probably be translated to normal HEX RGB values + (for `hsla()` and `rgba()`) the normal `fill-opacity` attribute.

See also: https://drafts.csswg.org/css-color.

**Comment by fsundermeyer** [comment]
I do not know what this is about or which problem needs to be fixed, Closing as wontfix.
