### ISSUE TITLE
Doc: Branding Guide: Add LICENSE for bash_ini_parser

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#333]
We will use https://github.com/rudimeier/bash_ini_parser to parse the branding ini-file. The parse is licensed under the BSD3-Clause and requires to include a copy of its license into the documentation.

https://github.com/rudimeier/bash_ini_parser/blob/master/LICENSE

As long as we are exclusively using it for branding stuff (might be useful for the DC-files as well), it should be sufficient to add the license to the branding guide.

**Comment by ghost** [comment]
> \2. Redistributions in binary form must reproduce the above copyright
>    notice, this list of conditions and the following disclaimer in the
>    documentation and/or other materials provided with the distribution.

Note the "and/or" ... maybe adding it to `COPYING` would be enough..?

**Comment by fsundermeyer** [comment]
Obsolete, we now have written a parser on our own.
