### ISSUE TITLE
When running with --debug, DAPS could validate generated FO/HTML

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#341]
It would be nice, to as an additional step, be able to validate that the outcome of all the processing is valid FO or HTML. This step should be non-fatal: Everything that builds otherwise should continue to build.

In essence, `$ daps -d DC-sth --debug outputformat` would take a bit longer than a normal run and might produce a few more messages. And stylesheet authors would know where to look.

**Comment by fsundermeyer** [comment]
I am not sure whether this will really help. 

For validating FO see http://www.oxygenxml.com/forum/topic7924.html
("_The problem with XSL-FO is that there is no tool which can fully and properly validate it. [...] The best validation for me is to process the XSL-FO to PDF_") If thtat's the proper way to validate FO, then daps already does it.

DAPS could validate HTML after a build by, for example, looping over all HTML files in the build directory and checking the files with $validator, but the same can easily be achieved by running e.g.

`$validator $(daps -d DC-SLES-security html)/*.html`

Closing as "WONTFIX"
