### ISSUE TITLE
Allow running daps-xmlformat on entire project

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#345]
It would be great if I could use daps-xmlformat as a target like this:

```
daps -d DC-sth xmlformat #or
daps -d DC-sth format-xml #or some other version of this.
```

**Comment by fsundermeyer** [comment]
Fixed with 2042f34

**Comment by ghost** [comment]
Awesome! Thanks. Ftr, the new command is `daps xmlformat`. Setting doc-impact label.

**Comment by fsundermeyer** [comment]
Re-opening for documentation
