### ISSUE TITLE
Make Product Names and Titles "Shareable"

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#347]
(Original idea from Tanja)
### Problem

Currently, all our doc repos contain an `entity-decl.ent` file. This file contains lots of product names and titles. When product names or titles change, all files should be updated (in theory).

At the moment we don't have a file which can be shared across different products and repos.
### Properties

It is assumed that the product parts change only, when
- a new product is requested, or
- an existing product changes its product name, title, or both (very rarely)

The  `entity-decl.ent` file needs to be splitted into a part with and without the product parts. The product part should contain only text (no elements to avoid any DocBook 4 vs. 5 problems) and no version number (this should go into the corresponding XML file).
### Possible Solutions
1. Using an URI in  `entity-decl.ent`, referring to the product specific parts:
   
   ``` xml
   <!-- file: entity-decl.ent -->
   <!ENTITY % products SYSTEM "http://www.example.org/common/products-decl.ent">
   % products;
   ```
2. Using [Git Submodules](http://www.git-scm.com/book/en/v2/Git-Tools-Submodules)
3. Use DAPS "Branding" project for the common content, as is done in Publican's "Brands" concept  (this would necessitate getting our Hack Week concept for DAPS shippable).
4. Something else?
### Discussion
1. Using an URI in the `entity-decl.ent`
   
   **Pros**: `products-decl.ent` will be downloaded when it's needed. It's always up-to-date.
   **Cons**: You can't build the product without Internet connection
2. Using Git Submodules
   
   **Pros**: Just another Git repo; doesn't need to be updated often, but could be (maybe?) done via Git hooks
   **Cons**: You need to actively update the submodule dir (maybe Git hooks come to the rescue?)

3. "Brands"
   **Pros**: One central location, always included
   **Cons**: Needs new DAPS functionality that includes the brand; If "brands" are RPMs like on Fedora, updating them will take pretty long (especially in OBS) and not everybody may be using the same version (i.e. there are content changes that depend on the version of a particular RPM) 

@taroth21, @sknorr: Anything to add from your side?

---

[**edit by sknorr** Under "Possible Solutions", added idea of using "brands".]

**Comment by ghost** [comment]
From the duplicate (issue #349), cwickert:

> ATM we have all entities defined in each and every project. We should look into splitting out at least global entities and project specific entities. A more fine-grained setup would be something like:
> - `global.ent`: user names and other *really really global stuff
> - `network.ent`: host and domain names etc.
> - `products.ent`: product names
> - optional specific declarations:
>   - `cloud.ent`,
>   - ...
> - `project.ent`: purely project-specific entities for that particular project
> 
> Note: First appearance of an entity overwrites later appearances.
> 
> Open questions:
> 1. Should we allow overwriting entities in projects?
> 2. Specific entities should include more general ones, so you only need to include `project.ent` which then includes all others. On the other hand many projects should not require a `project.ent`, so we cannot rely on it's presence.
> 3. Version control: The 'master' copy of each file should be under version control, but how exactly do we do this? git submodule? Simpy copy files around?

**Comment by sknorr** [comment]
Another note from me: Publican uses its "brands" concept for entity files, as well as legal texts and intro texts that are shared between projects. "Brands" are RPM packages that are installed in the system and then injected into the book when building.

Of course, this concept takes away quite a bit of flexibility.

**Comment by ghost** [comment]
-> https://github.com/openSUSE/doc-kit
