### ISSUE TITLE
Make entities global

### ISSUE THREAD

**Issue by cwickert** [openSUSE/daps#349]
ATM we have all entities defined in each and every project. We should look into splitting out at least global entities and project specific entities. A more fine-grained setup would be something like:
- `global.ent`: user names and other *really really global stuff
- `network.ent`: host and domain names etc.
- `products.ent`: product names
- optional specific declarations:
  - `cloud.ent`,
  - ...
- `project.ent`: purely project-specific entities for that particular project

Note: First appearance of an entity overwrites later appearances.

Open questions:
1. Should we allow overwriting entities in projects?
2. Specific entities should include more general ones, so you only need to include `project.ent` which then includes all others. On the other hand many projects should not require a `project.ent`, so we cannot rely on it's presence.
3. Version control: The 'master' copy of each file should be under version control, but how exactly do we do this? git submodule? Simpy copy files around?

**Comment by ghost** [comment]
Fwiw, related issue: https://github.com/openSUSE/daps/issues/347
