### ISSUE TITLE
Make the number of parallel jobs configurable

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#362]
By default DAPS calls make with -j <all_cores>. This is not always desireable. Maybe we should use half of them by default and make the setting configurable.

**Comment by ghost** [comment]
Using half the cores on e.g. a dual core machine (such as in a laptop) might mean using fewer cores than expected. It will also burn more energy as it will take longer before the processor can go to sleep again.

Why not use all cores by default but allow to scale down?

**Comment by fsundermeyer** [comment]
The following scenario always makes my desktop machine at home (AMD 6 Cores) freeze completely:
- machine already under load (3 or higher)
- running a CPU-intensive application with a virtual machine using two cores
- starting DAPS on a large project such as SLES

**Comment by fsundermeyer** [comment]
Fixed with commit   53270b6, handing over to documentation.

The new global switch --jobs lets you specify how mny parallel jobs to
use when processing XML and image with DAPS. If not specified, the
number is set to the number of CPU cores (as was done in previous versions).
