### ISSUE TITLE
db4tonovdoc.xsl generates invalid NovDoc

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#368]
Process the following file

Input file:
[booktest_docbook_for_conversion.xml.txt](https://github.com/openSUSE/daps/files/311758/booktest_docbook_for_conversion.xml.txt)

with

```
 /data/git/daps/libexec/daps-xslt --output /tmp/bigfile.xml \
 --stylesheet /<DAPS_CHECKOUT>/daps-xslt/migrate/db5to4/db4tonovdoc.xsl \
 --file /tmp/booktest_docbook_for_conversion.xml /usr/bin/xsltproc  
```

and validate the result with

```
xmllint --noent --postvalid --noout --xinclude /tmp/bigfile.xml
```

to get quite a few validation errors... .

**Comment by tomschr** [comment]
Fixed with commit ebdf2f25c
