### ISSUE TITLE
add 'aspell-en' to debian's 'optional' package list

### ISSUE THREAD

**Issue by tbazant** [openSUSE/daps#372]
aspell-en is not installed by default on debian 8 (jessie)
maybe it does not have to be aspell-en, or better aspel-*

**Comment by fsundermeyer** [comment]
Fixed in 17fe2dad3 but needs testing before branch feature/issues372 can be merged.

**Comment by fsundermeyer** [comment]
Apparently no testing was done - will merge and see what will happen.
