### ISSUE TITLE
Pretty confusing error messages when accidentally using -d instead of -m

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#374]
Trying to validate a release notes document... accidentally used `-d` instead of `-m`:

```
$ daps -d xml/release-notes.xml validate 
[dirname]/xml/release-notes.xml: line 1: syntax error near unexpected token `newline'
[dirname]/xml/release-notes.xml: line 1: `<?xml version="1.0"?>'
I/O error : Is a directory
[dirname]/xml:1: parser error : Document is empty

^
unable to parse[dirname]/xml
ERROR: Could not get DocBook version. Maybe [dirname]/xml is not well-formed?
```

This kind of response is expected but a) DAPS appears to be doing a bunch of things that are nonsense and b) the message is not helpful.
Could you improve the error message somewhat to instead suggest using `-m`?

**Comment by fsundermeyer** [comment]
The parser refactoring (4c00125926) also introduced a better error handling. Now DAPS errors out immediately with

ERROR: Error: Invalid key value "<?xml" in config-file /local/git/daps/doc/xml/book_daps_user.xml:1
