### ISSUE TITLE
CSS for Release notes in YaST makes low-level section titles too small

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#378]
(Before you close this, yes, this belongs here -- the YaST versions of release notes are formatted with stylesheets from this repository.)

In the SLE release notes, the technology previews section is one of the sections nested deepest. And there, the CSS appears to flail a little: section titles are printed in a below-para text size font.

**Comment by fsundermeyer** [comment]
Does not seem to have been a problem in the last 6 years ;-), so I am closing this as wontfix.
