### ISSUE TITLE
Conversion from GeekoDoc to NovDoc Has Some Issues

### ISSUE THREAD

**Issue by taroth21** [openSUSE/daps#383]
When running `daps online-docs` Frank and me stumbled across the following issues:

- [x] For the SLE HA Geo Quick Start, an additional ```<informalfigure/>``` was wrapped around the already existing  ```<informalfigure/>``` elements in the text. This happened only when using gitdaps (not for the packaged version), meaning this error must have been introduced only recently into the conversion stylesheet. 
- [x] the author files cannot be handled: Element author content does not follow the DTD, expecting (firstname , surname), got (personname ) - this seems to be fixed in GH already but not yet included in the package - please update package soon
- [x] Novdoc does not allow procedures in annotations. Please either update NovDoc to allow this, or convert procedures to orderedlists with the conversion script.
- [x] Please disallow "xreflabel" in GeekoDoc. Attributes do not get translated and therefore we should not allow xreflabel (and NovDoc does not support it anyway).
- [x] The stylesheet also failed on `<filename role='italic'/>` (don't ask me why anyone would use that, this was not in my repo); please strip the `role` attribute here
- [x] `<citetitle><systemitem/></citetitle>`, please strip systemitem, command etc. from citetitles.
- [x] `<informalfigure xml:id='...'>` failed, please strip the id here
- [x] para substeps para is not allowed in NovDoc - please either fix in GeekoDoc or adjust NovDoc accordingly

**Edit sknorr:** Added mine and Frank's issues here too.

**Comment by fsundermeyer** [comment]
1. <strike>Novdoc does not allow procedures in annotations. Please either update NovDoc to allow this, or convert procedures to orderedlists with the conversion script.</strike>
2. <strike>Please disallow "xreflabel" in GeekoDoc. Attributes do not get translated and therefore we should not allow xreflabel (and NovDoc does not support it anyway).</strike>

**Edit sknorr:** I have added Frank's issues to the description.

**Comment by tomschr** [comment]
@taroth21 I hope I fixed most of the issues you mentioned. There is only one left:
- [x] para substeps para is not allowed in NovDoc - please either fix in GeekoDoc or adjust NovDoc accordingly

If you have time, could you test it if it works? It's in the `feature/issue383` branch. I've tested it with the HA Geo QS and it validates for me.

**Comment by taroth21** [comment]
The fix should also be tested by @chabowski, @sknorr, @fsundermeyer  as the issues mentioned above were distributed across a number of different repos (see also today's reply to your mail from 2016-11-16).

**Comment by tomschr** [comment]
The last issue ( para substeps para is not allowed in NovDoc) has been fixed in commit  	https://github.com/openSUSE/geekodoc/commit/741bafe59f56d9.
