### ISSUE TITLE
online-docs: image warnings when not cleaning up

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#385]
When using an unclean build directory, online-docs tends to show a lot of warnings like:

```
tar: /data/sknorr/gits/doc-4sap/build/.images/color/s4s_install_license.png:
Warning: Cannot stat: No such file or directory
```

The tarball seems fine but otherwise. This also does not happen any more after cleaning up the build directory.

**Comment by fsundermeyer** [comment]
This may happen for a lot subcommands when you have moved files and images or when your build directory is very much outdated.
It is good practice to clean up before doing "online-docs" or "package-src".

Generally I do not consider this a bug. Unless I have no data to reproduce, there is little I can do. 

Closing as invalid.
