### ISSUE TITLE
Broken Parameters in DC file are not detected properly 

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#387]
DAPS does not seem to always check whether parameters in a DC file are broken.
For example, adding:

```
XSLTPARAM="\"""
```
to a DC file, leads to output like this:

```
> daps -d DC-SLES-installquick -vv html
[... snip ...]
   Profiling [...]/doc-sle/xml/deployment_prep_power_requirements.xm   Profiling[...]/doc-sle/xml/zypper.xmlThe following images are missing:
install_boot install_partitioner install_root install_timezone install_user install_welcome
   Validating...
   Successfully validated profiled sources.
Creating HTML pages
ERROR: Invalid XSLT processor: must be either xsltproc or saxon
/usr/share/daps/make/html.mk:270: recipe for target '[...]/doc-sle/build/SLES-installquick/html/art.sle.installquick/index.html' failed
make: *** [[...]/doc-sle/build/SLES-installquick/html/art.sle.installquick/index.html] Error 1
```

I would expect this to fail anyway but the error should be detected earlier, during parameter parsing, (ideally with a hint which line is the offending one).

**Comment by fsundermeyer** [comment]
The parameters specified in the config file are usually just passed to other programs, such as xsltproc. Therefore I cannot make a validation check for the key-value pairs.

However I have added a warning for "" values (and made a lot of improvements on the parser in  4c00125).

The error above stems from the way xsltproc handles parameters (it expects them in a given order, not all parameters are prefixed with "-" or "--").
