### ISSUE TITLE
Fail when building output with missing images (by default)

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#388]
We just had the issue that DAPS would validate & build output even when there were screenshots missing because of some improper merging. DAPS currently only shows a warning which can be missed easily:

```
The following images are missing:
install_boot install_partitioner install_root install_timezone install_user install_welcome
```
... and then builds successfully.

I think it would be good if DAPS failed in that case, at least by default. To override this, maybe add a parameter `--ignore-missing` which would ensure people kind of know what they are doing...

**Comment by fsundermeyer** [comment]
All packaging targets (package-*, online-docs, locdrop) exit with an error when images are missing. A warning for the other build targets seems sufficient to me.
