### ISSUE TITLE
daps-xmlformat writes name of config file into output

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#392]
Doing stuff like: `daps-xmlformat abc.xml > def.xml` leads to the output file not being valid XML, because `Using config file '/etc/daps/docbook-xmlformat.conf'` is always included as the first line.

This message could either be left away or directed to stdout.

This used to be already fixed but was unfixed in 2042f341237b079d130039b59c9d9d4c1c2e8661 .

**Comment by fsundermeyer** [comment]
Thanks for the pointer to 2042f34 ! I think I found an even better solution with f9e0b64.
