### ISSUE TITLE
liberation-fonts vs liberation2-fonts Requires in suse-xsl-stylesheets

### ISSUE THREAD

**Issue by zaitor** [openSUSE/daps#393]
Currently suse-xsl-stylesheets "hard" Requires liberation-fonts, but with the current freetype2 we have in Tumbleweed (possibly even in Leap 42.2/SLE 12SP2, liberation2-fonts is the recommended font.

Please consider changing this to suit the above.

See https://www.freetype.org/freetype2/docs/subpixel-hinting.html

This would not be an issue if liberation-fonts and  liberation2-fonts conflicted each other, but they do, so we need to work around this in this package.

Extrainfo: suse-xsl-stylesheets is the last package having a hard requires on  liberation-fonts

**Comment by ghost** [comment]
Closing here because this should better be tracked in the suse-xsl repo.
