### ISSUE TITLE
Spaces in path problem

### ISSUE THREAD

**Issue by mercadopatricio** [openSUSE/daps#397]
Hello, I'm new with daps, trying to make some documents, moving from latex to docbook. Currently made daps-init, and daps pdf, but seems I have errors with space char in my working path like this:

> patricio@book:/media/Clients/codex/My app/Aplication/trunk/Docs/Requirements specification/Document> daps pdf
warning: failed to load external entity "/media/Clients/codex/My"
unable to parse /media/Clients/codex/Mi
warning: failed to load external entity "app/Aplication/trunk/Docs/Requirements"
unable to parse ropero/Aplication/trunk/Docs/Requirements
warning: failed to load external entity "specification/Docs/xml/MAIN-daps-example.xml"
unable to parse specification/Docs/xml/MAIN-daps-example.xml
ERROR: Could not get DocBook version. Maybe /media/Clients/codex/My app/Aplication/trunk/Docs/Requirements specification/Document/xml/MAIN-daps-example.xml is not well-formed?
patricio@book:/media/Clients/codex/My app/Aplication/trunk/Docs/Requirements specification/Document> l
total 48
drwxr-xr-x 5 patricio users  4096 mar 13 22:28 ./
drwxr-xr-x 4 patricio users  4096 mar 13 20:10 ../
-rw-r--r-- 1 patricio users  1516 mar 13 22:28 DC-daps-example
-rw-r--r-- 1 patricio users   813 mar 13 22:12 Requirements specification.docbook
-rw-r--r-- 1 patricio users 16472 mar 13 20:10 Requirements specification.tex
drwxr-xr-x 2 patricio users  4096 mar 13 20:10 Imagenes/
drwxr-xr-x 3 patricio users  4096 mar 13 22:28 images/
drwxr-xr-x 2 patricio users  4096 mar 13 22:33 xml/
patricio@book:/media/Clients/codex/My app/Aplication/trunk/Docs/Requirements specification/Documento> 

What happen here?, are [365](https://github.com/openSUSE/daps/issues/365), [231](https://github.com/openSUSE/daps/issues/231) related?

my environment is openSUSE leap 42.2, daps 2.3.0

Thanks in advance :)

**Comment by tomschr** [comment]
Confirmed by Stefan

**Comment by fsundermeyer** [comment]
Hi,

DAPS uses GNU make. Make cannot handle spaces (and colons) in filenames (at least not reliable). Therefore the same restriction applies to DAPS as well. DAPS has other requirements on the directory structure and files:

* no spaces and colons in file and directory names
* DocBook files need to be named with the `.xml` extension
* DocBook and Entity files need to be placed inside an `xml/` directory (no subdirectories allowed here!!)
* Images need to be placed in `images/src`
  * png files need to go into `images/src/png`
  * svg files need to go into `images/src/svg`
  * ...
  * the basenames of all images (file name minus extension) have to be unique

The reason behind the special directory and file name structure is to make things for the writer as easy as possible. If you include files or images, you do not need to specify a path, the respective file name is all you need to enter. Whats more, images will automatically be trnsformed to

So for your project you need to make the following adjustments:

* make sure the above mentioned requirements are met
* make sure all <xi:include> and <imagedata> tags only contain filenames without a path

Looks like this needs to go into the documentation. Re-labeled the bug.

**Comment by mercadopatricio** [comment]
Uhm, it's ok, I think that same happen to latex referencing images. Is a little lazy to take care changing names. Hope update documentation.
Thank you :)

**Comment by fsundermeyer** [comment]
Re-opening because of the apparent lack of documentation (not fixed, yet).

**Comment by tomschr** [comment]
I think, most is documented already in https://opensuse.github.io/daps/doc/art.daps.quick.html#sec.daps.quick.basics.namereq:

* [x] no spaces and colons in file and directory names
* [x]  DocBook files need to be named with the .xml extension
* [x]  DocBook and Entity files need to be placed inside an `xml/` directory (no subdirectories allowed here!!)
* [x]  Images need to be placed in images/src (*)
* [x] png files need to go into images/src/png (*)
* [x] svg files need to go into images/src/svg (*)
* [x] the basenames of all images (file name minus extension) have to be unique

(*) These are already described in https://opensuse.github.io/daps/doc/art.daps.quick.html#sec.daps.quick.basics.dirstruct

@lightlace I think, only the one open item can be added to the section "File Name Requirements". Would you like to add it? It's file `phrases-decl.ent`, entity `daps-file-names-req`. Thanks! :+1:

**Comment by termdew** [comment]
Issue will be closed, as fix is already merged.
