### ISSUE TITLE
Links in pdf

### ISSUE THREAD

**Issue by mercadopatricio** [openSUSE/daps#398]
Hi, it's me again, I can't find the way to appear links inside PDF files as cross reference. I mean, I have:
`<term xml:id="RFADCA01" xreflabel="RFADCA01">RFADCA01</term>` and `<link endterm='RFADCA01'/>` . In HTML view link properly, but in PDF file appear text reference but no link, no mouse pointer change neither. How to achieve it?

Thanks in advance

**Comment by ghost** [comment]
`<xref linkend="..."/>` is the most common version. If you want just parts of the title of the element, you can experiment with the `xrefstyle` attribute.
