### ISSUE TITLE
Investigate Docker on Travis

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#409]
Currently, we don't test for different distributions. Testing is done manually in most cases which is suboptimal.

The idea would be to utilize Docker on Travis. It was first presented on the [oSC 2017](https://media.ccc.de/v/1354-continuous-integration-using-travis-and-docker) from Ladislav Slezák. In [his blog](https://blog.ladslezak.cz/2017/03/28/docker_at_travis/) he describes this technique.

For examples, see the Snapper repo: https://github.com/openSUSE/snapper

**Comment by fsundermeyer** [comment]
Obsolete.
