### ISSUE TITLE
Tab completion creates error message

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#411]
I tried...
```
daps -d DC-SLES-security spellcheck --ro[TAB]
```

and got this error message (with correct completion appended):

```
/usr/share/daps/lib/daps_functions: line 2082: help_lang: command not foundotid
```

The same happens with other options for `spellcheck` too. (DAPS 2.4.0 from OBS)

**Comment by fsundermeyer** [comment]
Fixed with e0ee28c65

An updated SUSE RPM package is also available from Documentation:Tools
