### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#413]
It would be cool to be able to use videos in DAPS documentation, to be able to re-use existing short screencasts/talks/... (Just an idea, maybe something for an upcoming hackweek.)

What I would imagine is that as a user, you get the following:

* HTML: inline video, that can be started after clicking on the preview image.
* PDF/EPUB: preview image, overlaid with web link (QR code??) that can be visited with mobile phone.

Pieces that would need to fall into place to make that happen:

1. general: definition of a standard format (probably WebM = Matroska+VP9+Vorbis/Opus)
2. DAPS: ability to handle such videos (i.e. copy them to the right dir etc.)
2. DAPS: *maybe* some conversion abilities (only from other standard formats such MP4+H.264+AAC, OGG+Vorbis+Theora) -- however, MP4 conversion would definitely depend on patent-restricted software which might be a non-starter
3. DAPS: ability to generate a representative frame that can be inserted in HTML as a preview, and in PDF as the stand-in for the video. Should be easy enough with ffmpeg or similar.
4. Stylesheets/schema: Possibility to add a short link (think bit.ly or similar) to the PDF that allows watching the video. It would need to be possible 
6. "server component"/black box: These videos then need to be reliably served from $somewhere. So we need a server that is able to reliably convert the shortened URLs that are printed in PDFs into the URL of the correct video file.

**Comment by fsundermeyer** [comment]
Shipping viedeos directly embedded in the docs makes little sense for a lot of reasons. Referencing to videos hosted on a dedicated video platform is the way to go (and that does not require any changes in DAPS). WONTFIX
