### ISSUE TITLE
Add support for LibreOffice Draw files

### ISSUE THREAD

**Issue by dmpop** [openSUSE/daps#415]
Add support for .odg files.

**Comment by ghost** [comment]
LibreOffice can export/open SVG files...

**Comment by dmpop** [comment]
I know, but I was asked to create an issue for that. Also, once converted to SVG, ODG files can't be edited in Draw, no?

**Comment by ghost** [comment]
You can open and edit SVGs in Draw. (Not sure about fidelity here -- I opened an SVG originally created in Inkscape and it didn't look completely correct. Not sure if Draw behaves much better when it opens SVGs created by itself.)

Anyway, I guess ODG might make sense as an input format -- Draw is easier to use than Inkscape.

However, it seems it would be very hard to handle this without adding a dependency on LibreOffice to DAPS... Inkscape does not open Draw files. While converting to SVG using hand-written XSLT is probably possible, I am not sure anyone wants to spend time on that.

**Comment by lightlace** [comment]
There is a solution called "unoconv".
https://github.com/dagwieers/unoconv

I tested it and it works.. therefore i'm looking now how to integrate it in our source code.

**Comment by fsundermeyer** [comment]
Fixed with 8895781
