### ISSUE TITLE
DAPS Won't Built With UTF-8 Characters in XML Filenames

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#416]
### Problem description
(Taken from [DAPS SF forum 'Fail to include external files'](https://sourceforge.net/p/daps/discussion/General/thread/6d5e27b8/))

When you create an XML file with a UTF-8 character (for example `MAIN-Especificación-de-requerimientos.xml`, see the **ó** character = U+00F3 = LATIN SMALL LETTER O WITH ACUTE) you get some strange XInclude errors (slightly reformatted to make it more readable):

```
/home/patricio/Docbook/build/.profiled/noprofile/MAIN-Especificación-de-requerimientos.xml:552:45: 
warning: Include operation failed, reverting to fallback.
Resource error reading file as XML (href='Glosario-Gestos.xml').
Reason: no protocol: Glosario-Gestos.xml
```

I haven't found yet the tool to blame.

### Expected behavior
Filenames with UTF-8 characters can be used without any problems.

If we can't solve this, we should document that as a recommendation in our User Guide.

### Steps to reproduce the behavior

1. Run `daps-init` and create a small example project
1. Rename the MAIN xml file to contain a UTF-8 character
1. Built the project.

Could this related to #397?

**Comment by termdew** [comment]
I just created a example project via
`daps-init --docdir daps-utf/ --name "Especificación-de-requerimientos"`
After that i ran `daps -d DC-Especificación-de-requerimientos html` in the `daps-utf` directory and it built just fine.

Did that on Tumbleweed.

One should make sure that the `locale` has UTF-8 inside.

Can be closed now, i guess.
