### ISSUE TITLE
DAPS can't handle capitalized file extensions in image names (e.g. *.PNG)

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#436]
### Problem description
I had some images named *.PNG instead of *.png. The images were capitalized correctly (i.e. with capital PNG) in the DocBook file that referenced them.

* The images are missing in PDF and HTML output
* daps list-images-missing showed them as missing

### Expected behavior
DAPS should recognize images with capital-letter file extensions.

### Steps to reproduce the behavior
Try to feed DAPS images with ugly capitalized file extensions...

**Comment by fsundermeyer** [comment]
I do not see any reason to fix this - filenames on Linux are case-sensitive and therefore *.PNG is the wrong file extension. Why not fixing the file name(s)?

I admit that the error message is not ideal and will therefore keep this issue open.
Maybe it's easier to accept uppercase suffixes than fixing the error message...

**Comment by fsundermeyer** [comment]
Will not be fixed, but should be properly documented.

**Comment by fsundermeyer** [comment]
Fixed with 6e97f73
