### ISSUE TITLE
Write useful xml:base into profiled MAIN and root element of bigfile

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#461]
### Problem description

The style checker checks which source file a certain part of the document is coming from by looking at xml:base attributes. However, iirc, we don't have a usable xml:base attribute in the MAIN file of a document (either empty or non-existing, need to check). Hence, the style checker shows no file information for the MAIN file.

Toms points at this file as the likely culprit:
daps-xslt/profiling/base-profile.xsl

### Expected behavior

Write xml:base everywhere.

### Steps to reproduce the behavior

`daps -d ... stylecheck`, see the "in file" meta information of messages.

**Comment by fsundermeyer** [comment]
Profiled files and bigfiles all have xml:base set for MAIN. When creating a bigfile, an xml:base for MAIN is, of course, only set if you generate it for the complete set.

```
~ > ack -rl "xml:base" xml/MAIN* || echo "None"
None
~ > ack -rl "xml:base" build/.profiled/**/MAIN*
build/.profiled/x86_64_zseries_power_aarch64_kvm4x86_sles/MAIN.SLEDS.xml
build/.profiled/x86_64_zseries_power_aarch64_sles/MAIN.SLEDS.xml
build/.profiled/x86_64_zseries_power_kvm4x86_sled/MAIN.SLEDS.xml
~ > daps -d DC-SLES-all bigfile
Find the bigfile at:
/data/git/doc-sle/build/.tmp/SLES-all_bigfile.xml
~ > ack -l "MAIN" build/.tmp/book.sle.deployment_bigfile.xml
build/.tmp/book.sle.deployment_bigfile.xml
```

**Comment by ghost** [comment]
This works for doc-sle but there still appears to be a bug: It does not work on DAPS's own documentation. Not sure if that is somehow because of DocBook 4 (daps/doc) v/ 5 (doc-sle)..?

Quickly looking at the stylesheet I don't see anything too suspicious, though.

**Comment by fsundermeyer** [comment]
toms, could you have a look? Seems to be stylesheet-related.

**Comment by fsundermeyer** [comment]
No longer needed, the stylechecker will be replaced by vale (see #717 )
