### ISSUE TITLE
MF stylesheets do not support <entry/>'s "morerows" and "colspan" attributes

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#463]
Some of our tables look broken in the published HTML version because Micro Focus's stylesheets do not properly convert the morerows and colspan attributes of DocBook:

* morerows example: https://www.suse.com/documentation/suse-caasp-3/book_caasp_deployment/data/sec_caasp_installquick_sysreqs.html#sec_caasp_installquick_netreqs

* colspan example: https://www.suse.com/documentation/sles-15/book_quickstarts/data/sec_modules_what.html

We could try to work around both issues to some degree in db4tonovdoc.xsl:

* For morerows, we could insert additional empty `<entry/>`s in following rows. (Which would be a bit heavy-handed but likely even look ok.)
* For colspan, we could do the same (but in following columns of course). This would fix some glaring display issues but would be unlikely to look good.

@tomschr, @fsundermeyer What do you think? Work around this or leave as is?

**Comment by fsundermeyer** [comment]
Leave as is and open a bug for it in bnc. THis is no DAPS issue.

**Comment by ghost** [comment]
OK. Created: http://bugzilla.suse.com/show_bug.cgi?id=1103224
