### ISSUE TITLE
RPMLINT complains about permissions of XSLT stylesheet

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#469]
The repo version of this file is not executable, so I guess the Makefile is doing something wrong:

```
[   18s] daps-devel.noarch: W: script-without-shebang /usr/share/daps/libexec/xinclude.xsl
[   18s] This text file has executable bits set or is located in a path dedicated for
[   18s] executables, but lacks a shebang and cannot thus be executed.  If the file is
[   18s] meant to be an executable script, add the shebang, otherwise remove the
[   18s] executable bits or move the file elsewhere.
```

**Comment by fsundermeyer** [comment]
toms, can you please fix this?

**Comment by tomschr** [comment]
Of course, executable bits on a stylesheet is nonsense. However, inside the GitHub repo, it's correct:

```
$ ls -l libexec/xinclude.xsl
-rw-r--r-- 1 toms suse 1143 26. Jul 14:33 libexec/xinclude.xsl
```

Probably, there is a script which sets everything inside `libexec` as executable.

@fsundermeyer Could the autoconf(ig) tools change this?

**Comment by fsundermeyer** [comment]
I assume libexec is the wrong location

**Comment by tomschr** [comment]
Ok, after further investigation, it seems, the [`%attr` directive](http://ftp.rpm.org/max-rpm/s1-rpm-inside-files-list-directives.html) in the spec file worked so far.
