### ISSUE TITLE
Document DAPS configuration options

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#477]
### Problem description

Currently, DAPS contains a configuration file which is located at `/etc/daps/config`. However, the options therein are not available in our documentation

Reported by @r0ckarong.

### Expected behavior

Have a reference inside our documentation that documents these options.

**Comment by fsundermeyer** [comment]
I"d rather not want to fix this - /etc/daps/config contains all the documentation that is needed and IMHO it does not make sense to duplicate this within the manual.

**Comment by r0ckarong** [comment]
Yeah no, it's not that easy. Nowhere in the documentation for DAPS does this even mention this path.
I am OK if you amend the comments in the actual configuration file but foregoing those entirely and expecting people to find them by accident when A) they need them and B) they happen to ask you should not be acceptable for a shared corporate toolchain.

**Comment by r0ckarong** [comment]
Nevermind, reopening this. The browser was playing bullshit on me. I still believe the config file itself should contain more info on what the options do.
