### ISSUE TITLE
Cannot seem to be able to customize the stylesheets

### ISSUE THREAD

**Issue by lopippo** [openSUSE/daps#481]
Greetings,

I have installed the 3.0.0 version of DAPS. 
I go to the doc directory and create xslt/html.
In there I create the docbook.xsl file with the following contents:

<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:d="http://docbook.org/ns/docbook">

	<xsl:import href="http://docbook.sourceforge.net/release/xsl-ns/current/html/docbook.xsl"/>

	
	<xsl:attribute-set name="admonition.title.properties">
		<xsl:attribute name="font-size">20pt</xsl:attribute>
		<xsl:attribute name="font-weight">bold</xsl:attribute>
		<xsl:attribute name="hyphenate">false</xsl:attribute>
		<xsl:attribute name="keep-with-next.within-column">always</xsl:attribute>
	</xsl:attribute-set>

</xsl:stylesheet>

I modify the DC-daps-user file by adding this line:

STYLEROOT="xslt"

Then, I run the following command:

daps --verbosity=3 --dapsroot .. -d DC-daps-user html --single

And in the output I see the following line:

           STYLEROOT: /home/rusconi/webstuff/daps-3.0/doc/xslt

that seems to acknowledge that I want custom stylesheets.

But then in the remaining output (I set verbosity to 3) I never see that the customized stylesheets are used. Instead I can see this:

/home/rusconi/webstuff/daps-3.0/libexec/daps-xslt --param "show.comments=0" --param "use.id.as.filename=1" --stringparam "base.dir=/home/rusconi/webstuff/daps-3.0/doc/build/daps-user/single-html/book.daps.user/" --stringparam "draft.mode=no" --stringparam "img.src.path=images/" --stringparam "admon.graphics.path=static/images/" --stringparam "callout.graphics.path=static/images/callouts/" --stringparam "navig.graphics.path=static/images/" --stringparam "draft.watermark.image=static/images/draft.png"  --stringparam "rootid=book.daps.user"  --stringparam "converter.name=DAPS" --stringparam "converter.version=3.0.0" --stringparam "converter.url=https://opensuse.github.io/daps" \
   --stringparam glossentry.show.acronym=primary --stringparam homepage=https://github.com/openSUSE/daps --param variablelist.as.blocks=1 --param glossary.as.blocks=1 --param body.start.indent=0 --param double.sided=0 --param header.rule=0 --param footer.rule=0 --stringparam paper.type=A4 --stringparam body.font.family="'Charis SIL', CharisSIL, serif" --stringparam sans.font.family="'Open Sans', OpenSans, sans-serif" --stringparam monospace.font.family="'DejaVu Sans Mono', DejaVuSansMono, monospace" --stringparam symbol.font.family="'DejaVu Sans Mono', DejaVuSansMono, KoreanSans, UnBatang, 'Un Batang', 'WenQuanYi Micro Hei Mono', WenQuanYiMicroHeiMono, monospace" --stringparam homepage=https://github.com/openSUSE/daps --param suse.content=0   \
  --output /home/rusconi/webstuff/daps-3.0/doc/build/daps-user/single-html/book.daps.user/book.daps.user.html --xinclude --stylesheet /usr/share/xml/docbook/stylesheet/docbook-xsl/xhtml/docbook.xsl \
  --file /home/rusconi/webstuff/daps-3.0/doc/build/.profiled/x86_amd64_em64t_osuse_noquick/MAIN.DAPS.xml /usr/bin/xsltproc

As you can see, the stylesheet used is 

--stylesheet /usr/share/xml/docbook/stylesheet/docbook-xsl/xhtml/docbook.xsl

How can I make sure that my customizing stuff (in xslt/html and xslt/fo) is taken into account ?
In the user guide, a more thorough example would be very useful as far as stylesheet customization is concerned (for html and for fo).

Thank you for this wonderful package that I enjoy a lot nonetheless.

Filippo

**Comment by ghost** [comment]
Hi,

we're glad you like it anyway! Just a few suggestions for what you could try:

1. I think for the `html` target, DAPS uses the "xhtml" folder by default. Can you try renaming your "html" folder to that? If that does help, I am unsure whether the behavior is a bug but I guess a fallback solution from xhtml->html *might* make sense. 

2. DAPS tends to like absolute paths best. I see how that is unlikely to be a good permanent option for you, but just see if that causes the issue. If that does help, I'd say it's a bug.

**Comment by lopippo** [comment]
As a follow-up, this is my experience when trying to customize the stylesheet for fo (not html, as above):

Same procedure: put the same docbook.xsl file in  xslt/fo.
Then run the command
daps --verbosity=3 --dapsroot .. -d DC-daps-user pdf

This is the output I get:

```
Reading makefiles...
Updating goal targets....
 File 'pdf' does not exist.
     Prerequisite '/home/rusconi/webstuff/daps-3.0/doc/xslt/fo/docbook.xsl' is newer than target '/home/rusconi/webstuff/daps-3.0/doc/build/.tmp/book.daps.user-fop_color_en.fo'.
    Must remake target '/home/rusconi/webstuff/daps-3.0/doc/build/.tmp/book.daps.user-fop_color_en.fo'.
/home/rusconi/webstuff/daps-3.0/libexec/daps-xslt --xinclude --param "show.comments=0" --param "generate.permalink=0" --param "ulink.show=1" --stringparam "draft.mode=no" --stringparam "styleroot=" --param "format.print=0" --stringparam "img.src.path=/home/rusconi/webstuff/daps-3.0/doc/build/.images/color/" --param "fop1.extensions=1" --param "xep.extensions=0" --stringparam "rootid=book.daps.user"  \
      --stringparam "converter.name=DAPS" --stringparam "converter.version=3.0.0" --stringparam "converter.url=https://opensuse.github.io/daps"  --stringparam glossentry.show.acronym=primary --stringparam homepage=https://github.com/openSUSE/daps --param variablelist.as.blocks=1 --param glossary.as.blocks=1 --param body.start.indent=0 --param double.sided=0 --param header.rule=0 --param footer.rule=0 --stringparam paper.type=A4 --stringparam body.font.family="'Charis SIL', CharisSIL, serif" --stringparam sans.font.family="'Open Sans', OpenSans, sans-serif" --stringparam monospace.font.family="'DejaVu Sans Mono', DejaVuSansMono, monospace" --stringparam symbol.font.family="'DejaVu Sans Mono', DejaVuSansMono, KoreanSans, UnBatang, 'Un Batang', 'WenQuanYi Micro Hei Mono', WenQuanYiMicroHeiMono, monospace" --stringparam homepage=https://github.com/openSUSE/daps --param suse.content=0  \
     --output /home/rusconi/webstuff/daps-3.0/doc/build/.tmp/book.daps.user-fop_color_en.fo --stylesheet /home/rusconi/webstuff/daps-3.0/doc/xslt/fo/docbook.xsl \
    --file /home/rusconi/webstuff/daps-3.0/doc/build/.profiled/x86_amd64_em64t_osuse_noquick/MAIN.DAPS.xml /usr/bin/xsltproc  \
    ;
Note: namesp. add : added namespace before processing              DAPS Documentation
Attributed 4596 IDs for element, cleaned up 0
    Successfully remade target file '/home/rusconi/webstuff/daps-3.0/doc/build/.tmp/book.daps.user-fop_color_en.fo'.
     File '/home/rusconi/webstuff/daps-3.0/doc/build/.tmp/static/images' does not exist.
       File '/home/rusconi/webstuff/daps-3.0/doc/build/.tmp/static' does not exist.
      Must remake target '/home/rusconi/webstuff/daps-3.0/doc/build/.tmp/static'.
mkdir -p /home/rusconi/webstuff/daps-3.0/doc/build/.tmp/static
      Successfully remade target file '/home/rusconi/webstuff/daps-3.0/doc/build/.tmp/static'.
    Must remake target '/home/rusconi/webstuff/daps-3.0/doc/build/.tmp/static/images'.
(cd /home/rusconi/webstuff/daps-3.0/doc/build/.tmp/static && ln -sf )
ln: missing file operand
Try 'ln --help' for more information.
/home/rusconi/webstuff/daps-3.0/make/pdf.mk:152: recipe for target '/home/rusconi/webstuff/daps-3.0/doc/build/.tmp/static/images' failed
/home/rusconi/webstuff/daps-3.0/make/pdf.mk:151: *** [/home/rusconi/webstuff/daps-3.0/doc/build/.tmp/static/images] Error 1

#0  /home/rusconi/webstuff/daps-3.0/doc/build/.tmp/static/images at /home/rusconi/webstuff/daps-3.0/make/pdf.mk:151
#1  /home/rusconi/webstuff/daps-3.0/doc/build/daps-user/book.daps.user_color_en.pdf at /home/rusconi/webstuff/daps-3.0/make/pdf.mk:239
#2  pdf at /home/rusconi/webstuff/daps-3.0/make/pdf.mk:180

What is interesting here is that it seems that the customized stylesheet is taken into account, this time:
(see above the following bit:
--stylesheet /home/rusconi/webstuff/daps-3.0/doc/xslt/fo/docbook.xsl).
```

But then, there seems to be a problem with a symbolic link that cannot work because one of the parameters is missing.

Any help ?
Cheers,
Filippo

**Comment by lopippo** [comment]
sknorr: thank you so much for your answer.
I have moved xslt/html to xslt/xhtml, as you kindly suggested, and launched the same daps command as above, but I get the following:
Reading makefiles...
Fatal error: Could not find stylesheet images
/home/rusconi/webstuff/daps-3.0/make/html.mk:121: *** .  Stop.
Cheers,
Filippo

**Comment by lopippo** [comment]
sknorr: as for the abs path, this is what I did:

in the configuration file, replace "xslt" with the abs path:

STYLEROOT="/home/rusconi/webstuff/daps-3.0/doc/xslt

But that did not change anything.

Cheers,
Filippo

**Comment by ghost** [comment]
Re:
> Fatal error: Could not find stylesheet images
> /home/rusconi/webstuff/daps-3.0/make/html.mk:121: *** . Stop.

I'd wager that's a better error than the one before. ^^
Can you try symlinking `/usr/share/xml/docbook/stylesheet/nwalsh/current/images/` to `images` within your custom stylesheet directory. (Assuming you are on openSUSE, if you are on a non-SUSE system, the path to the original DocBook stylesheets may be different.)

Re:
> in the configuration file, replace "xslt" with the abs path:
> STYLEROOT="/home/rusconi/webstuff/daps-3.0/doc/xslt

Then that's not it, which is good, I think.

**Comment by lopippo** [comment]
sknorr:

I did the following:
cd xslt && ln -sf /usr/share/xml/docbook/stylesheet/nwalsh/images ./images

Then I run the command (note the abs path to the DC file):
daps -d $(pwd)/DC-daps-user --verbosity=3 html --single

The output is the following:

```
Using MAIN file /home/rusconi/webstuff/daps-3.0/doc/xml/MAIN.DAPS.xml
---------------

        DAPS VERSION: 3.0.0

             DOC_DIR: /home/rusconi/webstuff/daps-3.0/doc
           BUILD_DIR: /home/rusconi/webstuff/daps-3.0/doc/build
            DAPSROOT: /usr/local/share/daps
             DOCCONF: /home/rusconi/webstuff/daps-3.0/doc/DC-daps-user
                BOOK: daps-user

           PROFILING: On
            PROFARCH: x86;amd64;em64t
              PROFOS: osuse;noquick

     DOCBOOK_VERSION: 4
        DOCBOOK5_RNG: 
        DBSTYLE_VERS: 1.79.1

           STYLEROOT: /home/rusconi/webstuff/daps-3.0/doc/xslt
      STYLEROOT_VERS: Not available
  FALLBACK_STYLEROOT: /usr/share/xml/docbook/stylesheet/docbook-xsl
   FB_STYLEROOT_VERS: Not available
            EPUB_CSS: 
            HTML_CSS: 

       PDF FORMATTER: fop
[warning] /usr/bin/fop: JVM flavor 'sun' not understood
   FORMATTER VERSION: FOP Version 2.1
   FORMATTER WRAPPER: /usr/local/share/daps/libexec/daps-fop
    FORMATTER CONFIG: 

            MAKE_CMD: /usr/bin/remake -f /usr/local/share/daps/make/selector.mk --debug=b -j1 html 
       XSLTPROCESSOR: /usr/bin/xsltproc
   XML_CATALOG_FILES: /etc/xml/catalog

---------------

Reading makefiles...
Updating goal targets....
 File 'html' does not exist.
   File 'list-images-multisrc' does not exist.
  Must remake target 'list-images-multisrc'.
  Successfully remade target file 'list-images-multisrc'.
   File 'list-images-missing' does not exist.
  Must remake target 'list-images-missing'.
  Successfully remade target file 'list-images-missing'.
   File 'copy_inline_images_html' does not exist.
  Must remake target 'copy_inline_images_html'.
for IMG in /home/rusconi/webstuff/daps-3.0/doc/build/.images/color/daps_chklink_report.png; do cp -rL --remove-destination $IMG /home/rusconi/webstuff/daps-3.0/doc/build/daps-user/single-html/book.daps.user/images; done
  Successfully remade target file 'copy_inline_images_html'.
   File 'copy_static_images_html' does not exist.
  Must remake target 'copy_static_images_html'.
tar cph --exclude-vcs -C /usr/share/xml/docbook/stylesheet/docbook-xsl/ images | \
          (cd /home/rusconi/webstuff/daps-3.0/doc/build/daps-user/single-html/book.daps.user/static; tar xpv) >/dev/null
  Successfully remade target file 'copy_static_images_html'.
Must remake target 'html'.
Single HTML book built with REMARKS=0, DRAFT=no and META=0:
/home/rusconi/webstuff/daps-3.0/doc/build/daps-user/single-html/book.daps.user/
Successfully remade target file 'html'.
```


Ah, and I set this in the xslt/html/docbook.xsl file:
``
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:d="http://docbook.org/ns/docbook">

	<xsl:import href="http://docbook.sourceforge.net/release/xsl-ns/current/html/docbook.xsl"/>

	
	<xsl:param name="linenumbering.everyNth">5</xsl:param>

</xsl:stylesheet>
``

Hoping that it would be evident in the output html file.

But I cannot see any numbering of the lines in the html file.

What customization would you suggest to make sure it has to be visible if the actual custom stylesheet were taken into account ?
Cheers,
Filippo

**Comment by ghost** [comment]
Hm, I have no experience with that parameter. Could you try a more aggressive customization like:

```
<xsl:template match="para|d:para" priority="1000">
  <h1>If this random nonsense comes out at the end, at least the customization works.</h1>
</xsl:template>
```

Also, always run DAPS with --force after you've updated stylesheets. When rebuilding, DAPS normally only takes into account changes to the DocBook files and images but not changes to the stylesheets.

**Comment by lopippo** [comment]
sknorr:
Fantastic, we are narrowing down... Indeed, the --force parameter to daps triggers the error when using the customized stylesheets. Before, we had a full build, but without taking into account the customizations.

Now we have this error:

```
$ daps --force -d $(pwd)/DC-daps-user --verbosity=3 html --single
Using MAIN file /home/rusconi/webstuff/daps-3.0/doc/xml/MAIN.DAPS.xml
---------------

        DAPS VERSION: 3.0.0

             DOC_DIR: /home/rusconi/webstuff/daps-3.0/doc
           BUILD_DIR: /home/rusconi/webstuff/daps-3.0/doc/build
            DAPSROOT: /usr/local/share/daps
             DOCCONF: /home/rusconi/webstuff/daps-3.0/doc/DC-daps-user
                BOOK: daps-user

           PROFILING: On
            PROFARCH: x86;amd64;em64t
              PROFOS: osuse;noquick

     DOCBOOK_VERSION: 4
        DOCBOOK5_RNG: 
        DBSTYLE_VERS: 1.79.1

           STYLEROOT: /home/rusconi/webstuff/daps-3.0/doc/xslt
      STYLEROOT_VERS: Not available
  FALLBACK_STYLEROOT: /usr/share/xml/docbook/stylesheet/docbook-xsl
   FB_STYLEROOT_VERS: Not available
            EPUB_CSS: 
            HTML_CSS: 

       PDF FORMATTER: fop
[warning] /usr/bin/fop: JVM flavor 'sun' not understood
   FORMATTER VERSION: FOP Version 2.1
   FORMATTER WRAPPER: /usr/local/share/daps/libexec/daps-fop
    FORMATTER CONFIG: 

            MAKE_CMD: /usr/bin/remake -f /usr/local/share/daps/make/selector.mk --debug=b -j1 --always-make html 
       XSLTPROCESSOR: /usr/bin/xsltproc
   XML_CATALOG_FILES: /etc/xml/catalog

---------------

Reading makefiles...
Updating goal targets....
 File 'html' does not exist.
      Must remake target '/home/rusconi/webstuff/daps-3.0/doc/build/.profiled/x86_amd64_em64t_osuse_noquick'.
mkdir -p /home/rusconi/webstuff/daps-3.0/doc/build/.profiled/x86_amd64_em64t_osuse_noquick
      Successfully remade target file '/home/rusconi/webstuff/daps-3.0/doc/build/.profiled/x86_amd64_em64t_osuse_noquick'.
    Must remake target '/home/rusconi/webstuff/daps-3.0/doc/build/.profiled/x86_amd64_em64t_osuse_noquick/MAIN.DAPS.xml'.
/usr/local/share/daps/libexec/daps-xslt --output /home/rusconi/webstuff/daps-3.0/doc/build/.profiled/x86_amd64_em64t_osuse_noquick/MAIN.DAPS.xml --stringparam "profile.arch=x86;amd64;em64t" --stringparam "profile.os=osuse;noquick" --param "show.comments=0"  \
  --stringparam "filename=MAIN.DAPS.xml" \
  --stylesheet /etc/daps-xslt/profiling/docbook45-profile.xsl --file /home/rusconi/webstuff/daps-3.0/doc/xml/MAIN.DAPS.xml /usr/bin/xsltproc
warning: failed to load external entity "/etc/daps-xslt/profiling/docbook45-profile.xsl"
cannot parse /etc/daps-xslt/profiling/docbook45-profile.xsl
/usr/local/share/daps/make/profiling.mk:117: recipe for target '/home/rusconi/webstuff/daps-3.0/doc/build/.profiled/x86_amd64_em64t_osuse_noquick/MAIN.DAPS.xml' failed
/usr/local/share/daps/make/profiling.mk:87: *** [/home/rusconi/webstuff/daps-3.0/doc/build/.profiled/x86_amd64_em64t_osuse_noquick/MAIN.DAPS.xml] Error 4

#0  /home/rusconi/webstuff/daps-3.0/doc/build/.profiled/x86_amd64_em64t_osuse_noquick/MAIN.DAPS.xml at /usr/local/share/daps/make/profiling.mk:87
#1  /home/rusconi/webstuff/daps-3.0/doc/build/daps-user/single-html/book.daps.user/book.daps.user.html at /usr/local/share/daps/make/html.mk:268
#2  html at /usr/local/share/daps/make/html.mk:192
```

How odd that now it pretends to build against 

DOCBOOK_VERSION: 4

Nowhere do it tell the publishing system that I want docbook version 4.

Where does the  --stylesheet /etc/daps-xslt/profiling/docbook45-profile.xsl bit come from ?

Cheers,
Filippo

Ah, and by the way, I am on Debian GNU/Linux, and installed the daps system after successfully building it using make install --prefix=/usr/local. That /etc/daps-xslt/profiling/docbook45-profile.xsl should thus be in /usr/local/etc. But that directory is empty.

**Comment by ghost** [comment]
> Where does the --stylesheet /etc/daps-xslt/profiling/docbook45-profile.xsl bit come from ?

Since you're running DAPS directly from the repo afaict, I think you should be able to defeat that by running daps with `--dapsroot /path/to/git/repo/of/daps`.

**Comment by lopippo** [comment]
sknorr:

Great, we are approaching ! Your last suggestion fixed the /etc/daps-xslt/profiling/docbook45-profile.xsl-related problem. But:

$ ../bin/daps --force --dapsroot /home/rusconi/webstuff/daps-3.0 -d $(pwd)/DC-daps-user --verbosity=3 html --single

provide lots of output. Amongst which the following:

  Must remake target '/home/rusconi/webstuff/daps-3.0/doc/build/daps-user/single-html/book.daps.user/book.daps.user.html'.
/home/rusconi/webstuff/daps-3.0/libexec/daps-xslt --param "show.comments=0" --param "use.id.as.filename=1" --stringparam "base.dir=/home/rusconi/webstuff/daps-3.0/doc/build/daps-user/single-html/book.daps.user/" --stringparam "draft.mode=no" --stringparam "img.src.path=images/" --stringparam "admon.graphics.path=static/images/" --stringparam "callout.graphics.path=static/images/callouts/" --stringparam "navig.graphics.path=static/images/" --stringparam "draft.watermark.image=static/images/draft.png"  --stringparam "rootid=book.daps.user"  --stringparam "converter.name=DAPS" --stringparam "converter.version=3.0.0" --stringparam "converter.url=https://opensuse.github.io/daps" \
   --stringparam glossentry.show.acronym=primary --param variablelist.as.blocks=1 --param glossary.as.blocks=1 --param body.start.indent=0 --param double.sided=0 --param header.rule=0 --param footer.rule=0 --stringparam paper.type=A4 --stringparam body.font.family="'Charis SIL', CharisSIL, serif" --stringparam sans.font.family="'Open Sans', OpenSans, sans-serif" --stringparam monospace.font.family="'DejaVu Sans Mono', DejaVuSansMono, monospace" --stringparam symbol.font.family="'DejaVu Sans Mono', DejaVuSansMono, KoreanSans, UnBatang, 'Un Batang', 'WenQuanYi Micro Hei Mono', WenQuanYiMicroHeiMono, monospace" --stringparam homepage=https://github.com/openSUSE/daps --param suse.content=0   \
  --output /home/rusconi/webstuff/daps-3.0/doc/build/daps-user/single-html/book.daps.user/book.daps.user.html --xinclude --stylesheet /usr/share/xml/docbook/stylesheet/docbook-xsl/xhtml/docbook.xsl \
  --file /home/rusconi/webstuff/daps-3.0/doc/build/.profiled/x86_amd64_em64t_osuse_noquick/MAIN.DAPS.xml /usr/bin/xsltproc

See that the xls stylesheet is still --stylesheet /usr/share/xml/docbook/stylesheet/docbook-xsl/xhtml ?

Now, I took that command line and it change that bit of information to 

--stylesheet /home/rusconi/webstuff/daps-3.0/doc/xslt/html/docbook.xsl

AND AND AND with the customization that you suggested IT WORKED.

So, left is to determine why the customization layer is not taken into account properly in the command line of the make file.

THANK YOU so much for your help.

Cheers,
Filippo

**Comment by lopippo** [comment]
sknorr: 
It might be of interest to know that the pdf target works fine with the work we did earlier. This command works perfectly fine:

../bin/daps --force --dapsroot /home/rusconi/webstuff/daps-3.0 -d $(pwd)/DC-daps-user --verbosity=3 pdf

which means that, contrary to the html target, this time the customized stylesheets are picked up. 

Maybe this is a good hint ?
Cheers,
Filippo

**Comment by fsundermeyer** [comment]
Hi,

first, we were a bit fast with the 3.0 release tag - I did a few updates today (mainly packaging related) and will probably rewrite the release tag tomorrow. You may want to update your repo.

Regarding your problem:

DAPS expects the same directory structure under $(STYLEROOT) as in `/usr/share/xml/docbook/stylesheet/nwalsh/current/` (or whereve they are located on Debian). You may leave out some directories, but if you want to create HTML, you need to have

${STYLEROOT}/xhtml
${STYLEROOT}/images

for PDF you need ${STYLEROOT}/fo, ${STYLEROOT}/images and so forth.

If that would not be the case, the STYLEROOT parameter would have to be different for each output format, That would either result in a different parameter for each output format or a different DC-file for each format - I wanted to avoid both.
The images directory is required for annotation images, callouts, etc. (For HTML-Builds you may optionally create a "static" directory which can also contain Javascript and CSS, see the documentation for details).

So why did your builds did not fail when providing a wrong styleroot parameter?

When you create custom stylesheets, you usually do not create stylesheets for all output formats DocBook supports. You focus on--let's say HTML. To prevent you from copying all the upstream stuff to your custom stylesheet directory, DAPS automatically falls back to the upstream stylesheets. That also happens when DAPS cannot find any directories to use (which was the case with your original approach).

Why having to use `--force`?

DAPS generates a lot of files - images get automatically converted, intermediate files such as FO are generated and last but not least, the resulting files such as PDF. Building them is time consuming. DAPS uses GNU make as backend and makes use of make's feature to only re-generate stuff when the sources have changed. This way files unnecessary rebuilds are avoided - when you for example have not changed the sources since the last PDF build, a new build will not create any new file.
make does this by checking dependencies. However, I cannot use the stylesheet as a dependency, since I do not know which one the user will use. As a result, DAPS will not rebuild when you change the stylesheet. Usually this is not a problem, because one does not change the stylesheet but rather the sources.
However, when you develop new stylesheets and want to test them with DAPS, this can quickly become annoying. For testing I suggest to create an alias for daps that includes the --force option.

HTH!

**Comment by ghost** [comment]
@lopippo did you follow the suggestion of moving `/home/rusconi/webstuff/daps-3.0/doc/xslt/html` -> `/home/rusconi/webstuff/daps-3.0/doc/xslt/xhtml`? DAPS uses the `xhtml` dir by default, methinks.

**Comment by lopippo** [comment]
fsundermeyer:
So many thanks for taking your time to explain all this in detail. Yeah, I guess I have understood the directory structure (names of directories mimicking the ones in the distribution) and all the concepts about not recreating Makefile targets that had not been touched (with the caveat of the stylesheets which need --force).

sknorr:
Yes, I tried at the time you suggested that 'mv xslt/html xslt/xhtml' operation but at that time my trials failed, maybe for other reasons. Fact is, now the build seems fine even without hand-fixing the xsltproc command --stylesheet parameter as it is correctly set now:
--stylesheet /home/rusconi/devel/docbook/msxpertsuite/minexpert/xslt/xhtml/docbook.xsl

So I guess everything is fixed.
Hats off to you!
Cheers, Filippo

**Comment by lopippo** [comment]
Greetings, 

I have studied both the user guide and quick guide and I found the graphical output (html and pdf) absolutely fantastic. Is it possible to have the customization stylesheets that were used for these publications ?
Thank you for your patience!
Cheers,
Filippo

**Comment by ghost** [comment]
Most certainly you can -- packaged on openSUSE as `suse-xsl-stylesheets`, upstream at https://github.com/openSUSE/suse-xsl .

**Comment by lopippo** [comment]
sknorr: wonderful, that's very neat, I'll study that material then. Thank you!
Cheers,
Filippo

PS As a Debian Developer I am starting to contemplate the possibility of packaging the DAPS software for Debian (not the SuSe stylesheets, maybe ;-). I'll keep you posted on that eventuality.

**Comment by fsundermeyer** [comment]
> PS As a Debian Developer I am starting to contemplate the possibility of 
> packaging the DAPS software for Debian (not the SuSe stylesheets, maybe ;-). I'll > keep you posted on that eventuality.

Great! Iwould love to see it in Debian. We already had some contributions for Debian packaging, but did not went any further, since nobody from the dev team is a Debian packager. Maybe the files will be of help for you (although there are probably not 1005 up to date):

https://github.com/openSUSE/daps/tree/develop/packaging/debian

In the parent directory (packaging) you will find the DAPS spec file for SUSE RPM builds. This may also be of help. Do not hesitate to contact me, if you have questions.

**Comment by lopippo** [comment]
fsundermeyer:
Thank you for the pointers. I'll gain more confidence with the daps/stylesheets ecosystem first, then check at the packaging you tell.

I have just built the docbook5 version of the SuSe https://github.com/openSUSE/suse-xsl stylesheets. I edited the Makefile, setting prefix to /usr/local. Now I want to run the tests. I need to find the location of dapscompare, I guess. Where are the sources for this program?
Thank you,
Cheers,
Filippo

**Comment by lopippo** [comment]
fsundermeyer:
Ah, found the dapscompare repos. Not so easy to install... I'll see if I can make without the tests...
Cheers, Filippo

**Comment by fsundermeyer** [comment]
Note that DAPS has no dependencies on the suse-xsl-stylesheets (we require them in our spec file because all SUSE documentation (which is using these stylesheets) is built with DAPS. It is easier and less error prone, to require the SUSE stylesheets at a single place (DAPS) rather than with each documentation package.

In order to work, DAPS only requires the DocBook4 _or_ the DocBook5 stylesheets--depending on which DocBook version you plan to support by default. You may also require both DocBook stylesheet versions.

**Comment by lopippo** [comment]
Greetings,
I have been using DAPS happily while heavily customizing the stylesheets, using the SUSE ones as a starting point. Thank you for sharing these, so generously commented as to serve as a stylesheet-tweaking manual!
I have a question :  I am fond of the Garamond type and I have configured fop (the xml config file) to use them. However, the new config is not "sensed" by DAPS. I would like to know how I can configure DAPS to automatically add -c $HOME/.fop/fop.xconf to the fop command line. Or should I go and modify the daps script ? Or there might be some better solution ?

Thanks again for this very powerful software package. I am still interested in packaging that for Debian, but could not find the time to do it.

Cheers,
Filippo

**Comment by fsundermeyer** [comment]
DAPS has got a variable named "FOP_CMD_OPTIONS" (see /etc/daps/config) which you can set to "-c <PATH_TO_CONFIG>".

You have three possibilities to set DAPS variables:

1. System-wide in /etc/daps/config
2. Per user in ~/.config/daps/dapsrc
3. Per project in the respective DC-files

See /etc/daps/config for documentation. General documentation is available at the top of the file, followed by explanations for each setting.

Note that is is very likely not a good idea to use "$HOME/<PATH>" when choosing option 1 and 3... ;-)

**Comment by lopippo** [comment]
Greetings,

thank you for your answer. I am experience an odd behaviour that I would like to describe (please, bear with me, the experiment log has some lines):

Project in ${srcDir}
All commands below ran from this project source directory.

First condition with no FOP_CMD_OPTIONS set in DC file
======================================================

In this condition, my font config is not used.

Build the project using:

	daps --force -d ${srcDir}/DC-massxpert-user-manual --verbosity=3 pdf

The build goes fine. The fop command that is output at the end of the pdf file
rendering goes like:

[INFO] FOUserAgent - Rendered page #75.
fop command: fop -q  "${srcDir}/build/.tmp/massxpert-user-manual-fop_color_en.fo ${srcDir}/build/massxpert-user-manual/massxpert-user-manual_color_en.pdf"

(note the double-quotes around the input file and the output file)

Second condition with FOP_CMD_OPTIONS set in DC file
======================================================

The following line is added to the DC file:

FOP_CMD_OPTIONS="-c fop.xconf"

The file fop.xconf is locate in ${srcDir}

Build the project using:

	daps --force -d ${srcDir}/DC-massxpert-user-manual --verbosity=3 pdf

The making of all the image targets goes fine, but then, at fop invocation I
have the following error:

[ERROR] FOP - Exception <java.io.FileNotFoundException: fop.xconf (No such file or directory)>java.io.FileNotFoundException: fop.xconf (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at org.apache.fop.apps.FopConfParser.<init>(FopConfParser.java:127)
        at org.apache.fop.cli.CommandLineOptions.setUserConfig(CommandLineOptions.java:1024)
        at org.apache.fop.cli.CommandLineOptions.parse(CommandLineOptions.java:173)
        at org.apache.fop.cli.Main.startFOP(Main.java:169)
        at org.apache.fop.cli.Main.main(Main.java:217)

fop command: fop -q -c fop.xconf "${srcDir}/build/.tmp/massxpert-user-manual-fop_color_en.fo ${srcDir}/build/massxpert-user-manual/massxpert-user-manual_color_en.pdf"

(note that the double-quotes this time do not include the -c fop.xconf file).

Since the message complained that the fop.xconf file was not found, I ran the
command manually like this:

fop command: fop -q -c ${srcDir}/fop.xconf "${srcDir}/build/.tmp/massxpert-user-manual-fop_color_en.fo ${srcDir}/build/massxpert-user-manual/massxpert-user-manua   l_color_en.pdf"

The error here is no more about the fop.xconf file not being found but about the
output file not being specified:

[ERROR] FOP - Exception <org.apache.fop.apps.FOPException: No output file specified>org.apache.fop.apps.FOPException: No output file specified
        at org.apache.fop.cli.CommandLineOptions.checkSettings(CommandLineOptions.java:916)
        at org.apache.fop.cli.CommandLineOptions.parse(CommandLineOptions.java:172)
        at org.apache.fop.cli.Main.startFOP(Main.java:169)
        at org.apache.fop.cli.Main.main(Main.java:217)

I reasoned that the two double-quoted files where interpreted as one single file
and removed the double-quotes:

fop -q -c fop.xconf ${srcDir}/build/.tmp/massxpert-user-manual-fop_color_en.fo ${srcDir}/build/massxpert-user-manual/massxpert-user-manual_color_en.pdf

The rendering is fine, with my fonts showing up in the document (which
demonstrates that the -c fop.xconf syntax is fine without the full path).

I then tried putting all the fop stuff between double-quotes:

fop "-q -c fop.xconf ${srcDir}/build/.tmp/massxpert-user-manual-fop_color_en.fo ${srcDir}/build/massxpert-user-manual/massxpert-user-manual_color_en.pdf"

Failure.

My take on this is that daps-fo creates a command line for running fo that has a
problem with quoting ? What is odd is that the first build condition did run
fine (without trying to specify the fop config file) *and* with the
double-quotes!

Also, what is the -q flag for? As of 

$ fop -version
[warning] /usr/bin/fop: JVM flavor 'sun' not understood
FOP Version 2.3

the -q flag is not present in the man page nor using "fop --help".

Thank you for your help deciphering all this!

Cheers,
Filippo

**Comment by fsundermeyer** [comment]
You need to specify an absolute path for the config file, otherwise it will not be found.

Note to self:
Create a separate option "FOP_CONFIG" which can be passed to the `sanitize_path` function to allow relative paths.

**Comment by lopippo** [comment]
Greetings,

>You need to specify an absolute path for the config file, otherwise it will not be found.

Right, that fixed the issue.

Can I insist on this other aspect in a previous comment,

Also, what is the -q flag for? As of

$ fop -version
[warning] /usr/bin/fop: JVM flavor 'sun' not understood
FOP Version 2.3

the -q flag is not present in the man page nor using "fop --help".

Cheers,
Filippo

**Comment by ghost** [comment]
A very belated answer but I think -q is for quieting FOP which is otherwise a pretty noisy companion.

**Comment by fsundermeyer** [comment]
To me it looks like everything here is solved, closing.
