### ISSUE TITLE
Start work on Debian packaging

### ISSUE THREAD

**Issue by lopippo** [openSUSE/daps#487]
Greetings, fellow developers,

I am now starting the Debian packaging of the DAPS suite which I have now successfully used to generate the documentation for my software:
http://msxpertsuite.org/wiki/pmwiki.php/Main/UserManual

First step is to just run dpkg-buildpackage in the top source dir. But that step fails immediately because the old debian/patches/fix-xmlcatalog-output.patch does not apply anymore. This is something I cannot easily figure out. Please, help me step over this issue, and I'll go on with the packaging.

Thanks for your help!
Cheers,
Filippo

**Comment by lopippo** [comment]
As a follow-up, I have successfully built the package (might not yet be fully Debian-compliant) by removing the patches altogether, since at least one of them (the shebang stuff) does not make sense anymore. I'll keep sending updates on this channel. Please, tell me if you do not like this way of communicating.

**Comment by lopippo** [comment]
I have installed the Debian package that I made right now and used this installed daps to build my user manuals. That is very good news. I still have lots of details to fix, but we will be there!

**Comment by lopippo** [comment]
Well, I found that the packaging was well advanced already. There are two debian directories in the source tree. I used the one that had most recent changelog items (not in the packaging directory, but in the top source directory).

In debian, any program should have a man page explaining what it is for. The daps-xmlformat does not have a man page. Is it a program that daps uses internally or the end user might user it for formatting xml files? If so a man page could be created for that program.

**Comment by lopippo** [comment]
During testing of daps-xmlformat, I discovered that it does not work on Debian because the switches passed to the "which" program at line 55 do not exist in Debian (--skip-alias --skip-functions). This triggers an error that read like:

$ ./daps-xmlformat --help
Using config file '/home/rusconi/devel/packaging/daps/development/etc/docbook-xmlformat.conf'
./daps-xmlformat: line 60: Usage:: command not found

This is becase the which program issues a line

$ which --skip-alias --skip-functions xmlformat
Illegal option --
Usage: /usr/bin/which [-a] args

Can you confirm that this behaviour is specific to Debian ? If so I might need to patch the daps-xmlformat(.in) file.

Cheers,
Filippo

**Comment by fsundermeyer** [comment]
Sorry, for answering late, I have been very busy the last two weeks.

Not sure whether the "which" behaviour is Debian-Specific, or whether the options I have used are SUSE-specific ;-). It occurs in several places:

````
> ack -- "--skip-alias" .                                  
lib/xmlformat
29:        XMLFORMAT_CMD="$(which  --skip-alias --skip-functions "$_BINARY" 2>/dev/null)" && break
60:        DAPSXMLFORMAT="$(which --skip-alias --skip-functions daps-xmlformat 2>/dev/null)" || exit_on_error "Cannot find a daps-xmlformat executable"

lib/spellcheck
38:        if [[ $(which  --skip-alias --skip-functions "$P_SPELL_CHECKER" 2>/dev/null) ]]; then
49:                SPELL_CHECKER="$(which  --skip-alias --skip-functions "$SC" 2>/dev/null)"

bin/daps-xmlformat.in
55:    XMLFORMAT_CMD="$(which  --skip-alias --skip-functions "$_BINARY" 2>/dev/null)" && break

test/run_tests.sh
107:    which --skip-alias --skip-functions $_REQ >/dev/null 2>&1 || exit_on_error "Requirement $_REQ is not installed, exiting"
233:        which --skip-alias --skip-functions $_PROC >/dev/null 2>&1
242:    which --skip-alias --skip-functions /usr/bin/saxon6 >/dev/null 2>&1
284:                    which --skip-alias --skip-functions $_FOPROC >/dev/null 2>&1
````
For a first workaround I suggest that you patch it when building the Debian package.
I will have a closer look into it, other Debian-based distributions may also be affected, so it probably makes sense for me to patch it in DAPS...

**Comment by lopippo** [comment]
Greetings, 
daps is now in Debian; I could make it before freeze. So, most probably, daps will be in the next stable.
For the moment I kept the GPLv2+. 
https://packages.debian.org/sid/daps
Cheers,
Filippo

**Comment by fsundermeyer** [comment]
Looks like we can close this one...
