### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by lopippo** [openSUSE/daps#490]
Greetings, Fellow Developers,

in the debian/copyright file, we state what license is applicable to the software. I would like to put GLPv3+ for daps/* files.

Is this OK, given that 2+ allows for the option to use a later version ?

Cheers,
Filippo

**Comment by fsundermeyer** [comment]
According to https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ you can just say

    License: GPL-2+

meaning GPL 2 or later.
