### ISSUE TITLE
Missing man pages for programs

### ISSUE THREAD

**Issue by lopippo** [openSUSE/daps#491]
Greetings, 

I found that Debian lintian complains about three programs not having a man page:

W: daps: binary-without-manpage usr/bin/daps-auto
W: daps: binary-without-manpage usr/bin/daps-check-deps
W: daps: binary-without-manpage usr/bin/daps-xmlformat

It would be nice to have them generated automagically like the other ones (man/xml/*).

Cheers,
Filippo

PS For the moment, I am writing these but in a super-concise manner. Not suitable for upstream, I would say.

**Comment by fsundermeyer** [comment]
Added man pages for daps-xmlformat and daps-check-deps with 873b2add8a.

daps-auto has been replaced by autobuild/daps-autobuild and should have been deleted long ago. Did this with e7c5cc9684bd

**Comment by lopippo** [comment]
Wonderful, 
thanks a lot.
Filippo
