### ISSUE TITLE
Installing the contents of libexec makes a non-script file executable

### ISSUE THREAD

**Issue by lopippo** [openSUSE/daps#492]
Greetings,

I would like to report the fact that 

$ ls libexec:
-rw-r--r-- 1 1000 1000  1143 Feb  6 12:35 daps-xmlwellformed-xinclude.xsl

which is not executable gets its exec bit set after installation:

ls -l /tmp/usr/share/daps/libexec/daps-xmlwellformed-xinclude.xsl
-rwxr-xr-x 1 root root 1143 Feb  8 18:31 /tmp/usr/share/daps/libexec/daps-xmlwellformed-xinclude.xsl

The fact that we install an executable file while it is not a script is an error in Debian. Could you please fix that for next releases (if I am no mistaken somehow)?

Thanks, 
Filippo

**Comment by fsundermeyer** [comment]
Fixed temporarily with 11761df3 

@tomschr : Could you please have a look at moving the xsl file(s) to daps-xslt? You could use a placeholder like @libexecdir@ which I can automatically replace by the Makefile (this is what I do with other scripts). However, this will prevent the script from working when using a git checkout directly. Any chance we get both options working? (Setting a fixed path like /usr/share/daps/libexec is not an option).

**Comment by lopippo** [comment]
For the Debian package I simply removed the -x bit for that specific file in d/rules. This looks like the temp fix you did.

**Comment by ghost** [comment]
The "temporary fix" has already celebrated its second birthday ... should we just declare this issue fixed, @fsundermeyer ?

**Comment by fsundermeyer** [comment]
PR #635 will remove daps-xmlwellformed-xinclude.xsl entirely (and I will release a new version once this PR is merged), therefore this bug will no longer be valid. Therefore closing this.
