### ISSUE TITLE
Create better error message when MAIN file does not exist

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#494]
When the MAIN file referenced from a DC does not exist, DAPS prints a misleading error message:

```
# daps -d DC-suse-openstack-cloud-security validate
ERROR: Source files must reside in an "xml/" directory. "/path/to/repo/xml/MAIN.hos-imported.xml" is not a valid location.
```

Could you change the error message to something more easily understood, such as `ERROR: MAIN file "/path/to/repo/xml/MAIN.hos-imported.xml" does not exist.`?

**Comment by fsundermeyer** [comment]
Fixed with fbb3fd51bf03477a5aeba1cce43a42f1aeaee329
