### ISSUE TITLE
The 'autobubbletoc' Feature of the HTML Stylesheets is Broken

### ISSUE THREAD

**Issue by stefanq** [openSUSE/daps#496]
### Problem description
For the HTML output format DAPS generates a javascript based table of contents.
The javascript implementation of the TOC is capable to generate nested menus for section and sub-sections. Unfortunately this implementation (from 2012 or before) is broken for a very long time now and also unmaintained.
This means, navigating TOC entries works for top-level chapters only.

Also, the generation of nested toc-entries in the xhtml/autobubbletoc.xsl stylesheet which is a prerequisite is broken as well as it generates <div> TOC entries for chapters only but not for any section elements (but that can be easily fixed, see below).

### Expected behavior
The navigation features of a Javascript driven TOC in a DAPS generated single-page HTML document work as expected, i.e.

1. Clicking the "Contents" button in the navigation bar opens a list of chapters 
2. Hovering a chapter entry opens a list of the chapter's sections to the right
3. Hoverin a section entry opens a list of the section's sup-sections to the right
4. And so on
5. Clicking any chapter/section entry navigates to the beginning of the chapter/section.

Note: Step 5 actually works as expected (for chapters) as everyone can see with the DAPS HTML documentation.

### Steps to reproduce the behavior
1. Apply the patch to the xhtml/autobubbletoc.xsl stylesheet described in https://sourceforge.net/p/daps/discussion/General/thread/8b04b6d3/
2. Generate single-page XHTML of any DocBook 5 document with sections and subsections (maybe a modified Daps user guide).
2. Open the generated HTML in a browser
3. Clicking the "Contents" button in the navigation bar
=> The list of chapters is shown (expected)
4. Click a chapter entry
=> A list of sections is shown (which supposedly is as specified at the time when this has been implemented)
5. Click a section entry
=> no list of subsections is shown (unexpected)
6. Click the same chapter again
=> sections are shown to the right AND also the list of subsections (of the formerly selected section) are shown to the right.
=> Click or double-click for navigating a setction/subsection does not work (unexpected).

**Comment by stefanq** [comment]
A demonstration of how the nested table of contents generated on the fly by the js/sript.js (part of every generated HTML) looks like after a little patching of the xhtml/autobubbletoc.xsl:
![daps-issue496 github](https://user-images.githubusercontent.com/9786301/54612292-f6d14c80-4a58-11e9-9f86-bea015c22c21.png)

**Comment by stefanq** [comment]
Oops, accidentally closed this when providing a screenshot.

**Comment by fsundermeyer** [comment]
@sknorr Looks like one for you. You may weant to move it to suse-xsl...

**Comment by fsundermeyer** [comment]
This actually was a suse-xsl-stylesheet bug and we obviously forgot to move it accordingly. In the meantime we have moved on to a new version of stylesheets and the version that contained this bug is no longer maintained. Closing as wontifix (sorry).
