### ISSUE TITLE
Creation date in the pdf file

### ISSUE THREAD

**Issue by lopippo** [openSUSE/daps#497]
Greetings, DAPS developers,

in Debian, we try to implement "reproducible builds" as much as possible. My msxpertsuite software builds reproducibly unless for the pdf files generated by DAPS [0]. The un-reproducibility is due to the recording of the creation date in the pdf files. Looking at [1], I understand that fop does that data recording in the pdf metadata section.

My question: is there a way to configure DAPS to inhibit that date creation recording ?

Thank you so much for DAPS!

Cheers,
Filippo

0: https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/msxpertsuite.html
1: https://xmlgraphics.apache.org/fop/1.0/metadata.html

**Comment by ghost** [comment]
We have the same issue in openSUSE, see issue #482 ... but my knowledge since working on this then has not expanded. I think the better contacts for this topic are the FOP upstream maintainers.

We are certainly willing to fix this if you know how and the effort is reasonable. I will leave this bug open for the moment but may close later.

**Comment by lopippo** [comment]
I filed a bug report to them
https://issues.apache.org/jira/browse/FOP-2854

**Comment by fsundermeyer** [comment]
If I understand https://xmlgraphics.apache.org/fop/1.0/metadata.html correctly, creation date and modification date can be either set via the .fo file or via the FOP's FOUserAgent (whatever this is).

This information could be passed on the DAPS command line via e.g. --set-date (which we are already using with the package-pdf subcommand) and pass the date via parameter to the stylesheets, which in turn could create a .fo file with the creation/modification date set to the given date.

Alternatively, we could use something like --fix-date in DAPS and set a dummy date in the PDF.

Would this help?

**Comment by fsundermeyer** [comment]
OK, just read through issue #482 - this does not seem to work.
Closing this issue, since it was reported upstream.
