### ISSUE TITLE
[ADOC] Generating `online-docs` fails with DTD error

### ISSUE THREAD

**Issue by r0ckarong** [openSUSE/daps#499]
### Problem description

I'm trying to publish the first CaaSP v4 doc with DAPS and AsciiDoc. I can generate the outputs fine on their own on my machine. When I try to generate `online-docs` it fails with a DTD error.

File:
https://github.com/SUSE/doc-caasp/blob/adoc/adoc/quick-deployment.adoc

DC-File:
https://github.com/SUSE/doc-caasp/blob/adoc/DC-caasp-quickstart

~I noticed this was happening because I added the `adoc` branch to the susedoc.github.io config but no content shows up. I can not find out how to check on Travis if something fails or why (I don't even know where to log in or find the build responsible for this task, the HHG is sorely unhelpful about this).~

Is this something wrong with my input file? 
~Is this something broken on travis or with the build config?~

### Expected behavior

The docs build and get published as expected.

### Steps to reproduce the behavior

Attempt to generate online docs from above file using DAPS 3.0.

**Comment by r0ckarong** [comment]
The publishing was a different problem, the DTD error persists with `online-docs` parameter.

**Comment by ghost** [comment]
Hm, unfortunately, the Novdoc DTD expects data that we don't have :(

```
[...]doc-caasp/build/caasp-quickstart/online-docs/set_en_bigfile.xml:3: element bookinfo:
  validity error : Element bookinfo content does not follow the DTD, expecting (title ,
  productname+ , productnumber?, date? , releaseinfo? , titleabbrev? , legalnotice+ ,
  authorgroup* , abstract*), got (title date legalnotice authorgroup)
```

You're lacking a productname here and I don't know of a way to supply that in AsciiDoc (at least with `asciidoctor`-compatible AsciiDoc; with `asciidoc` you could supply a `-docinfo.xml` file but that is not supported in `asciidoctor`).

**Comment by fsundermeyer** [comment]
Contrary to the comment above, asciidoctor also supports the -docinfo.xml files. Providing such a file with the missing elements will solve the isue.
