### ISSUE TITLE
'daps optipng' messes up timestamps

### ISSUE THREAD

**Issue by cwickert** [openSUSE/daps#504]
### Problem description
`daps optipng` touches all images, even those that don't get optimized.

### Expected behavior
Timestamps of images that didn't get optimized should not change.

### Steps to reproduce the behavior
1. run `daps -d DC-FILE optipng`
2. even if not a single file has been optimized, all files have new timestamps

**Comment by fsundermeyer** [comment]
Works for me, I do not see timestamp changes on files not optimized.
