### ISSUE TITLE
[ADOC] DAPS ignores table centering in PDF

### ISSUE THREAD

**Issue by r0ckarong** [openSUSE/daps#506]
### Problem description

Asciidoc allows values in table cells to be positioned (left, center, right). This positioning is ignored.

### Expected behavior

Content formatting is honored by the converter and properly formatted in the output.

### Steps to reproduce the behavior

- Configure a table with aligned cell contents
- Convert to PDF with DAPS

```
==== Certificate keys

[options="header",cols="<,^,^"]
|===
|Path                         |Key type |Key length (bits)
|apiserver.key                |RSA      |2048
|apiserver-kubelet-client.key |RSA      |2048
|apiserver-etcd-client.key    |RSA      |2048
|etcd/server.key              |RSA      |2048
|etcd/healthcheck-client.key  |RSA      |2048
|etcd/peer.key                |RSA      |2048
|===
```

# Output from AsciiDoctor
![Screenshot_20190510_173026](https://user-images.githubusercontent.com/4920542/57538777-683ac680-7349-11e9-8f96-dcf72a8fce9b.png)

# Output from DAPS
![Screenshot_20190510_172806](https://user-images.githubusercontent.com/4920542/57538688-417c9000-7349-11e9-9d3e-d247bf3ab8d6.png)

**Comment by ghost** [comment]
This is a suse-xsl issue.
