### ISSUE TITLE
daps optipng does not reoptimize after an image changed

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#513]
`daps optipng` writes its optimization information into the EXIF data of the image itself. Unfortunately, that approach overlooks that images can be edited and will not be optimized anymore after editing.

E.g. while DAPS does not report any bloated images in the doc-sle repo, running plain `optipng` on the `images/src/png` dir, I get 13 (of 373) images which change because of the optimization.

Maybe it would be better to run `md5sum` (maybe there is an even cheaper hash function? we don't really care about the security of the hashes here) over the optimized files and store the results in a text file `images/src/.optimized` like this:

```
32378ae67[...]f png/image1.png
5544aace7[...]e png/image1.png
```

That would then allow DAPS to check which images have a different md5 sum and need to be re-optimized.

**Comment by fsundermeyer** [comment]
Fixed with c132a5f
