### ISSUE TITLE
The way we are using optipng is suboptimal for Git

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#514]
This is a problem that is largely social, though maybe there is a technical solution (which I don't know yet): In many cases, people first commit an image and later notice that is not yet optimized. Then they make another commit.

This is okay for when we build PDF/HTML where we only include the final optimized image.

For Git it is absolutely not optimal, and much worse than only storing the non-optimized image: Git has to store the original version and then later has to store the optimized version in addition, both as binary blobs.

If there was a way to force people to optimize before they first commit..?

**Comment by fsundermeyer** [comment]
No idea how to do this, WONTFIX
