### ISSUE TITLE
ADOC_ATTRIBUTES is either misdocumented or misimplemented

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#516]
The documentation for ADOC_ATTRIBUTES says [1] you can use:

```
ADOC_ATTRIBUTES="author=myself"
```

However, you actually have to use:

```
ADOC_ATTRIBUTES="--attribute author=myself"
```

Is this wishful thinking on the part of the documentation or is the implementation wrong currently?

(I'd rather like to see the documented version work, but for compatibility, in addition to the current actual version.)

[1] https://opensuse.github.io/daps/doc/daps-asciidoc.html#_command_line_options_and_configuration_settings_for_asciidoc

**Comment by fsundermeyer** [comment]
Doc error. Unfortunately it is not trivial implementing your whish, therefore I rather fixed the doc (also, works the same way with xslt parameters).

Fixed with afc1b087
