### ISSUE TITLE
[ADOC] Daps misinterprets escaped double square brackets as anchor

### ISSUE THREAD

**Issue by r0ckarong** [openSUSE/daps#517]
### Problem description

We have a document that describes a TOML file in which there is a `[[registry]]` element. The syntax for defining custom anchor IDs in asciidoc is double square brackets. DAPS somehow misinterprets this as an anchor definition even though we explicitly escaped the string.

```

The configuration is a sequence of `+[[registry]]+` entries. For example, a
single registry entry within that configuration could be added like this:

`/etc/containers/registries.conf`
[source,toml]
----
[[registry]]
blocked = false
insecure = false
location = "example.net/bar"
prefix = "example.com/foo"
mirror = [
    { location = "example-mirror-0.local", insecure = false },
    { location = "example-mirror-1.local", insecure = true, mirror-by-digest-only = true }
]
unqualified-search = false
----

Given an image name, a single `+[[registry]]+` TOML table is chosen based on its
`prefix` field.
```

```
asciidoctor: WARNING: admin-crio-registries.adoc: line 25: id assigned to anchor already in use: registry
asciidoctor: WARNING: admin-crio-registries.adoc: line 37: id assigned to anchor already in use: registry
asciidoctor: WARNING: admin-crio-registries.adoc: line 66: id assigned to anchor already in use: registry
asciidoctor: WARNING: admin-crio-registries.adoc: line 91: id assigned to anchor already in use: registry

```

### Expected behavior

The escaped strings `+[[registry]]+` is recognized as NOT being an anchor definition.

### Steps to reproduce the behavior

Use double square brackets in any asciidoc text and escape them using the `+` syntax modifier.

**Comment by ghost** [comment]
If this is an issue, it is an AsciiDoctor issue -- however, could you try with `+++` instead please? cf. https://asciidoctor.org/docs/asciidoc-writers-guide/#preventing-substitution

**Comment by r0ckarong** [comment]
`+++` didn't work. I got it to work now with `\[[registry]]`.

**Comment by fsundermeyer** [comment]
Yes, using the backslash seems to be the official way as the link sknorr provided suggests. Closing.
