### ISSUE TITLE
AsciiDoctor XML generation issues from sbp/SAP_S4HA10_SetupGuide-SLE15

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#519]
* This DC file is already using ADOC_POST
* I have not tried with the newest version of the ADOC_POST stylesheet, only with the version that ships in DAPS 3.0. It is possible that some of these are fixed already in unstable DAPS.

- [ ] ISSUE 1. Ye olde formalpara-should-be-example issue:

```
.File /usr/sap/{mySid}/SYS/profile/{mySid}_{myInstAscs}_{myVipNAscs}

[subs="attributes"]
----
Start_Program_01 = local $(_ENQ) pf=$(_PF)
----
```
  ->
```
<formalpara>
<title>File /usr/sap/EN2/SYS/profile/EN2_ASCS00_sapen2as</title>
<para>
<screen>Start_Program_01 = local $(_ENQ) pf=$(_PF)</screen>
</para>
</formalpara>
```

- [ ] ISSUE 2. AsciiDoc (and plain DocBook) allows paras with IDs: *facepalm*

```
[[multicluster]]
*Multinode cluster* setups mean cluster configurations with more than two nodes.
```

->

```
<para xml:id="multicluster"><emphasis role="strong">
  Multinode cluster</emphasis> setups mean cluster configurations with more than two nodes.
</para>
```

**Comment by fsundermeyer** [comment]
These issues have been fixed in the meantime
