### ISSUE TITLE
AsciiDoctor writes its own <date/> tag

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#521]
In our DocBook documents, we use a PI to insert a build date into the document, while using the build date is maybe not entirely ideal (mostly because the build date will change on every build, not just when documents have actually changed), at least that date is always up-to-date.

AsciiDoctor on the other hand automatically generates a DocBook `<date/>` tag based on the main file's mtime. That works great if your document has no include::s, but if it does and you don't change the main file much, the date starts falling behind the actual last change.

There is also no way to get a custom format for that date, it will always be YYYY-MM-DD (which admittedly is a good default).

You can't properly overwrite this \<date/\> from a -docinfo.xml file, because the \<date/\> you put into your -docinfo.xml file will appear later in the document than AsciiDoctor's, so the stylesheets will only pick up AsciiDoctor's date.

So, to get today's date into an AsciiDoc document, the best thing you can do currently is run `touch adoc/main-file.adoc` before building.

Not quite sure how to solve this. Options:
1. DAPS could run `touch main-file.adoc` before building. Not sure whether that would create issues with `make`'s document change mechanics.
2. The ADOC_POST stylesheet could filter AsciiDoctor-generated dates which would allow using DocBook-generated dates.

@chabowski had this issue with a bunch of SBPs.

**Comment by fsundermeyer** [comment]
A custom date  can be set with `ADOC_ATTRIBUTES="--attribute docdate=YYYY-MM-DD"` in the DC-file. INVALID
