### ISSUE TITLE
Excalibur issues on Tumbleweed [2019-08-22]

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#522]
@nkoranova noticed warning messages about excalibur missing on Tumbleweed when building PDFs:

```
/usr/bin/build-classpath: Could not find excalibur Java extension for this JVM
/usr/bin/build-classpath: error: Some specified jars were not found
```

* The only thing in DAPS that specifically mentions excalibur is a FOP classpath parameter (FOP_DEFAULT_JAVA_JARS)
* Nora can build documents nonetheless. So, apparently this is not strictly necessary.

Remains to check whether something is wrong in DAPS's classpath, in FOP's packaging or on Nora's machine.

Update 2021-03-26 (Toms): @tbazant can confirm that issue.

**Comment by fsundermeyer** [comment]
Not an issue on Tumbleweed anymore, I assume this was a temporary bug in TW.
