### ISSUE TITLE
asciidoctor --failure-level option is only known from v1.5.8 onward

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#523]
DAPS versions from the repo are now using the Asciidoctor option --failure-level (cf. 247de748982). That is a good thing. However, Leap 15.1 only ships AsciiDoctor 1.5.6.

AsciiDoctor 1.5.8 is the first version that knows this parameter. This means that DAPS now only works with either a package from Documentation:Tools or from Factory.

**Comment by fsundermeyer** [comment]
A asciidoctor version check was implemented with 588d54245
