### ISSUE TITLE
Find a new DAPS forum host

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#537]
DAPS currently has a forum on SourceForge (and it is the last SourceForge service we actively use). That's not ideal:

* SourceForge's interface is complicated and offers way more features than just a forum -> confusing
* you need a SourceForge account in addition to your GitHub account
* SourceForge is a ghost town which reflects on the forum as well
* the email threading of SourceForge threads is horrible

A selection of options that came to my mind after a bit of research:

## 1. Discourse
* standard: 100$/m
* free for open source, but only when Discourse deems a forum for us clearly necessary, there is an application period
* hosted on subdomain like daps.discourse.com
* is open-source itself, available as Docker container for self-hosting
* can be integrated into existing website with some customization
* no ads
* new community, needs separate accounts
* chic, uncomplicated, minimalist
* can subscribe to/answer via mail
* mobile apps exist

## 2. Reddit
* free with ads
* cannot be integrated into existing website but allows CSS customization
* large existing technical community, e.g. on r/linux, r/opensuse (but much more than that: memes, stories, etc, including violent/adult content)
* DAPS would have its own subreddit micro-community
  * however, reddit.com/r/daps is/was used by another community, so we'd need a different name like r/dapsdocs etc.
* mobile apps exist

## 3. Nabble
* free with ads
* minimal page header, so probably easy to integrate into website as an iframe etc.
* new community, very few existing accounts
* 2 variants:
  * as web forum
  * as mailing list archive on the web (allows posting mails as well)
* easy to use, minimalist
* provider can be a bit spammy, tries to foist its product on existing public mailing lists and motivates its users to reply from their web interface

## 4. Disqus
* 9$/m without ads
* free with ads
* integrates into existing websites using JS
* not a regular forum: meant to be used as a comment thread for blog posts, users can't just open a new thread
* should still be good enough as long as we create a release post on the website for each new release
* new community, many existing accounts

## 5. Reuse this issue tracker (and add a "forum"/"support" label)
* free, no ads, no new account necessary
* mixed in with bug reports
* may not always be clear if a new item is meant as a bug or a forum thread
* can subscribe to/answer via mail

## 6. New GitHub issue tracker
* free, no ads, no new account necessary
* necessitates creating a new otherwise unused GitHub repo -> confusion about empty repo and role of the two repos
* no mixing of bugs/forum (except when people are confused)
* can subscribe to/answer via mail

## 7. Random free PHPBB host with ads
* please no

**Comment by ghost** [comment]
@fsundermeyer @tomschr @taroth21 preferences?

**Comment by tomschr** [comment]
@sknorr Hmn... :thinking: ... I see your point.
From a maintenance and usability perspective, I would prefer to have code and "forums" on one site. For this reason, I would pick number 5 "Reuse this issue tracker". Everything is under one roof, I don't need to create a new account. :wink: 

Regarding your concerns:

> mixed in with bug reports
> may not always be clear if a new item is meant as a bug or a forum thread

This could be kind of directed when opening a new issue. We could use issue templates (see section [Configuring issue templates for your repository](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository).)

With such issue templates, I see the following benefits:

* We could create a "support" or "bug" template. Whenever a user creates a new issue, the user has to select one of these preconfigured templates.

* You can also automatically add labels or assignees to new issues. To create issue templates, go to https://github.com/openSUSE/daps/issues/templates/edit.

* We could create a project board which can display only support or bug issues (currently disabled in our DAPS repo). It looks similar to a Trello board, see the example https://github.com/python-semver/python-semver/projects/1.

* Filtering becomes less of a pain as you could show only "support", "bug", or both.

-----

Apart from the above, the list misses one feature in GitHub: [Discussions](https://help.github.com/en/github/building-a-strong-community/creating-a-team-discussion). :wink: 

Not sure if it's a viable alternative, but just for the sake of completeness, look here:
https://github.com/orgs/openSUSE/teams/documentation

Users can start discussions and we could answer them. What's a bit inappropriate is, it is a *team discussion* page, not a page for *daps discussion*. It is also a bit separated from our daps repo page.

On the other side, this would be the closest feature that could be used as a "forum".

**Comment by ghost** [comment]
Fwiw, I asked @cwickert informally yesterday and he too favored option 5., reusing this issue tracker.

> Apart from the above, the list misses one feature in GitHub: Discussions. wink
> Not sure if it's a viable alternative, but just for the sake of completeness, look here:
https://github.com/orgs/openSUSE/teams/documentation

No, not usable :(. I just logged in with my secondary GitHub account (which is not a member of the openSUSE org) and the discussion page is not even visible to anyone outside the team.

**Comment by ghost** [comment]
Ok, Frank was in favor of using this issue tracker as well. I created a forum label and changed a couple of links. There are now "Forum" links in the readme and on the homepage.

**Comment by tomschr** [comment]
Thanks for your efforts! :+1: 

What about the issue templates that I've described above? Couldn't we simplify the creation of "forum" discussion with that?

It's really easy to create one. When we have these in place, the user has to select from "Bug" or "Forum/Discussion" only (just as an example). With the issue templates, the right label can already be preselected. That makes it less dangerous to have an issue mislabeled.

Would that be an option? :wink:

**Comment by ghost** [comment]
Sorry -- I didn't read your comment again yesterday. I did something concerning the issue templates in the .github dir of the repo. I didn't realize there were two kinds of issue templates now.

But for what it's worth, I added new-post link into the README and on the homepage that set the right label automatically. Might that be enough?

**Comment by ghost** [comment]
Ok, done now. Turns out, you just need to add a few lines of metadata to the existing Markdown templates.

**Comment by tomschr** [comment]
Thanks Stefan! :+1:
