### ISSUE TITLE
Improve validation to make it more useful in scripts

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#547]
* make a test of missing images an optional part of validate
* consider checking tables an optional part of validate (see issue #532)
* evaluate whether daps validate can _always_ return >0 in case a validation error occurred (at least when used in pipes or scripts)

**Comment by ghost** [comment]
update:
* images & IDs are done: 6508a930bddb5d2ea47c8e90a20c333917b2bbb6
* tables script is at least shipped but not properly integrated: 8f4d286f3c52619ede89a29589019101c4df4811

**Comment by ghost** [comment]
I think this can be closed

* #532 is in the works anyway.
* I no longer know what this refers to: "evaluate whether daps validate can always return >0 in case a validation error occurred (at least when used in pipes or scripts)". I see `$? == 2` when `daps validate` fails and that is good.
