### ISSUE TITLE
error: element "listitem" incomplete

### ISSUE THREAD

**Issue by dmbyte** [openSUSE/daps#551]
### Problem description
document: https://github.com/SUSE/ra-ses-isv
/root/Veeam9-SES5/build/.profiled/noprofile/mydoc.xml:271:12: error: element "listitem" incomplete; expected element "address", "anchor", "annotation", "bibliolist", "blockquote", "bridgehead", "calloutlist", "caution", "classsynopsis", "cmdsynopsis", "constraintdef", "constructorsynopsis", "destructorsynopsis", "epigraph", "equation", "example", "fieldsynopsis", "figure", "formalpara", "funcsynopsis", "glosslist", "important", "indexterm", "informalequation", "informalexample", "informalfigure", "informaltable", "itemizedlist", "literallayout", "mediaobject", "methodsynopsis", "msgset", "note", "ns:include", "orderedlist", "para", "procedure", "productionset", "programlisting", "programlistingco", "qandaset", "remark", "revhistory", "screen", "screenco", "screenshot", "segmentedlist", "sidebar", "simpara", "simplelist", "synopsis", "table", "task", "tip", "variablelist" or "warning" (with xmlns:ns="http://www.w3.org/2001/XInclude")

**Comment by ghost** [comment]
@dmbyte Thanks for the report! Unfortunately, the repo seems to be private, so I can't take a look. Could you either open it for me or copy the relevant portion of the source ADOC?

**Comment by dmbyte** [comment]
Frank fixed the source doc.  Seems to be something about handling lists of lists.  Repo shared so you can see what he changed.

**Comment by fsundermeyer** [comment]
Oops, forgot to close the bug.
