### ISSUE TITLE
images not proper sized

### ISSUE THREAD

**Issue by dmbyte** [openSUSE/daps#555]
ra-ses-isv repo, VMware67-SES5 doc.  two images are not honoring the scalewidth parameter in the image definition.  email me for the PDF example if needed.

**Comment by ghost** [comment]
Iiuc, the parameter is called scale**d**width with an extra D. So is that maybe just a typo?

**Comment by dmbyte** [comment]
duh.. thanks @sknorr

**Comment by ghost** [comment]
OK :) I guess I'll close this then.
