### ISSUE TITLE
Rename 'daps checklink' to 'daps linkcheck' 

### ISSUE THREAD

**Issue by taroth21** [openSUSE/daps#559]
### Problem description
As checking links is part of the final checks before a release, I usually run 'daps spellcheck', 'daps stylecheck', and  'daps checklink' in a row. I always stumble across 'daps checklink' (and even need to look it up) because it does not match the other two, as check here is the first part of the compound. In addition, as the command checks more than one link, I'm always tempted to type 'daps checklinks' (plural).  
### Expected behavior
Reaming the command to match the other two commands that have *check* in their name would make it easier to remember and more consistent.

**Comment by ghost** [comment]
Resolved with a08a59e
