### ISSUE TITLE
DAPS Branding [sf#56]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#56]
**Reported by taroth21 on 2012-03-23 08:42 UTC**
Would be nice to have some kind of basic CI for DAPS -> in accordance to the DAPS Homepage, create a DAPS branding for the stylesheets? (e.g. layout for Quick Start, fonts, etc.)

References:
- http://docbook.sourceforge.net/release/xsl/current/doc/index.html

**Comment by tomschr** [comment]
**Commented by tom_schr on 2012-03-23 09:00**
I would recommend the following, minimal parameters:

For FO/PDF:

```
body.font.family=<Some Open Source Serif Font>
body.start.indent=0em or 2em # Depends on if we want to indent our main text
component.label.includes.part.label=1
monospace.font.family=<Some Open Source Monospace Font>
paper.type="A4"
sans.font.family=<Some Open Source Sans Serif Font>
section.autolabel=1
section.autolabel.max.depth=6 # Maybe more, maybe less
section.label.includes.component.label=1
symbol.font.family=<Some Open Source Symbol Font>
variablelist.as.blocks=1 # _Extremly_ important :)
```

**Comment by tomschr** [comment]
**Commented by tom_schr on 2012-03-23 09:06**
For XHTML, here are the recommended, minimal parameters:

```
html.stylesheet=<OUR DAPS CSS>
section.autolabel=1
section.autolabel.max.depth=6 # Consistent with FO
section.label.includes.component.label=1
use.id.as.filename=1
```
- Description has changed:

Diff:

```

--- old 
+++ new 
@@ -1,1 +1,4 @@
 Would be nice to have some kind of basic CI for DAPS -> in accordance to the DAPS Homepage, create a DAPS branding for the stylesheets? (e.g. layout for Quick Start, fonts, etc.)
+
+References:
+* http://docbook.sourceforge.net/release/xsl/current/doc/index.html

```
- **labels**: Stylesheets --> Stylesheets, xslt

**Comment by tomschr** [comment]
**Commented by tom_schr on 2014-10-24 13:34**
Useful to add this to the DC file:

```
XSLTPARAM="$XSLTPARAM --stringparam body.start.indent 0em"
XSLTPARAM="$XSLTPARAM --stringparam paper.type 'A4'"
```

This approach makes it easier to disable one parameter.

**Comment by fsundermeyer** [comment]
Was fixed quite some time ago when Stefan created DAPS stylesheets.
