### ISSUE TITLE
Repo Maintenance: Switch to master/main and use .gitattributes

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#560]
* Get rid of develop and use master/main to be consistent with other repos
  ** requires adjustement of mails and scripts
* use .gitattributes for packaging, see https://github.com/openSUSE/suse-xsl/blob/master/.gitattributes and https://github.com/openSUSE/suse-xsl/blob/master/Makefile#L151
  ** obsoletes packaging/exclude-files_for_daps_package.txt

**Comment by ghost** [comment]
ftr, ~~I switched this repo to using the master branch  already~~ we switched to using the main branch, I fixed the repo README (but nothing else), and you set up the .gitattributes file.

Missing pieces:
* maybe have to fix other READMEs, the documentation, and scripts
* use Git for building tarballs

**Comment by fsundermeyer** [comment]
This was fixed long ago.
