### ISSUE TITLE
The ./configure script does not recognixe libreoffice-draw on Debian buster

### ISSUE THREAD

**Issue by tbazant** [openSUSE/daps#564]
`./configure.ac` looks for the `oodraw` binary, while Debian has only `lodraw` available

**Comment by tomschr** [comment]
During a Teams call, we found out that under Leap, we have both: `/usr/bin/oodraw` and `/usr/bin/lodraw`. The first one is a hardlink.
If I remember correctly, `oodraw` was the old name and during the renaming from OpenOffice to LibreOffice, these names were affected too.
