### ISSUE TITLE
Make validation of IDs in sync with Travis

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#566]
### Problem description

Currently, we have [ID checks in Travis](https://github.com/openSUSE/doc-ci/blame/master/travis/travis.sh#L301-L302), but not with daps. This leads to unfortunate situations: you validate your document and all is green, but it fails on Travis.

### Expected behavior

Probably it should be enough to add an "ID validation check" in daps. From the above link, we currently have:

```
BIGFILE=$($DAPS_SR -d "$DCFILE" bigfile)
FAILING_IDS=$(xml sel -t -v '//@xml:id|//@id' "$BIGFILE" | grep -P '[^-a-zA-Z0-9]' | sed -r 's/(^|$)/"/g')
```

Of course you need to translate that into daps/Makefile logic.

Maybe this line would be obsolete if GeekoDoc is able to check against our ID syntax. I would prefer to have that thing in GeekoDo too. For the time being, this fix would be probably easier.

If the above works, maybe we could simplify the part in the above `travis.sh` script.

**Comment by ghost** [comment]
This sounds like a bad idea -- it would explicitly code another SUSE use case into DAPS. I think we should avoid that as much as possible. What are the obstacles to solving this as part of GeekoDoc?

**Comment by ghost** [comment]
I think this can be closed now, since Toms has merged an equivalent fix in to Geekodoc.
