### ISSUE TITLE
ASCIIDoc: formalpara and para/screen doesn't validate in GeekoDoc

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#569]
### Problem description

The following ASCIIDoc code:

```adoc
.Title
---
code1
code2
---
```

generates this XML fragment:

```xml
<formalpara>
<title>Title</title>
<para>
<screen>code1
code2</screen>
</para>
</formalpara>
```

In GeekoDoc, a block element (in this case `screen`) must not be placed inside a `para`. This step happens during the postprocessing step (stylesheet `daps-xslt/asciidoc/postprocess.xsl`).

### Expected behavior

In this case, such a structure is probably better expressed as an `example`:

```xml
<example>
   <title>Title</title>
   <screen>code1
code2</screen>
</example>
```

**Comment by ghost** [comment]
I looked at the document for some examples, and more complete examples look more like this (note the wrapping informalexample elements):

```
<informalexample>
<formalpara>
<title>Get Nodes List Operation</title>
<para>
<screen>suse01:~ # stonith -t external/ec2 profile=&lt;AWS-profile&gt; tag=&lt;aws_tag_containing_hostname&gt; -l</screen>
</para>
</formalpara>
<itemizedlist>
<listitem>
<para>The above command should return something like:</para>
</listitem>
</itemizedlist>
<screen>external/ec2[4193]: info: status check for i-abcdefg0123456789 is running
external/ec2[4183]: info: Operation gethosts passed
suse01
suse02</screen>
</informalexample>
```

```
<informalexample>
<formalpara>
<title>Fencing Operation</title>
<para>
<screen>suse01:~ # stonith -t external/ec2 profile=&lt;AWS-profile&gt; port=&lt;cluster-node2&gt; tag=&lt;aws_tag_containing_hostname&gt; -T off &lt;cluster-node2&gt;</screen>
</para>
</formalpara>
</informalexample>
```

**Comment by tomschr** [comment]
Thanks. I've looked into the AD source and would like to highlight one point. In your last example, this is the corresponding AD source:

```adoc
==============================
  
.Fencing Operation

[subs="specialchars,attributes"]
----
{sapnode1}:~ # stonith -t external/ec2 profile=<AWS-profile> port=<cluster-node2> tag=<aws_tag_containing_hostname> -T off <cluster-node2>
----

==============================
```

If you remove the `=` lines, you don't get the `informalexample` in the result XML. So this element depends on which AD structure is used by the writer.

**Comment by ghost** [comment]
So, #570 addresses the issue for the most part. However, with more complicated constructs like the following, it will nest examples:

```
====
.Title 1
----
screen content
----

A paragraph of text.

.Title 2
----
screen content 2
----
====
```

This would result in:

```
<example>
  <title>Title 1</title>
  <screen>screen content  1</screen>
  <para>
   A paragraph of text.
  </para>
  <example>
    <title>Title 2</title>
    <screen>screen content 2</screen>
  </example>
</example>
```

That is absolutely not ideal and @tomschr and I discussed whether to outright fail on such constructs, or return an xsl:message asking authors to simplify their construction, or maybe just change the autor-desired structure to avoid nesting example elements..
