### ISSUE TITLE
daps fails when directory names contain spaces

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#572]
### Problem description

If your directory name contains one or more spaces, daps fails.

Reported by Sascha Manns. Many thanks! :+1: 

### Expected behavior

Spaces in directory names aren't important. Daps shouldn't fail.

### Steps to reproduce problem

```shell
$ git clone git@github.com:SUSE/doc-slert.git "/tmp/repo test/doc-slert"
$ cd "/tmp/repo test/doc-slert"
$ daps -v -d DC-SLE-RT-quick validate
warning: failed to load external entity "/tmp/repo"
unable to parse /tmp/repo
warning: failed to load external entity "test/doc-slert/xml/MAIN.SLERT.xml"
unable to parse test/doc-slert/xml/MAIN.SLERT.xml
ERROR: Could not get DocBook version. Maybe /tmp/repo test/doc-slert/xml/MAIN.SLERT.xml is not well-formed?
```

The directory name is cut off as you can see in this line:

```
warning: failed to load external entity "test/doc-slert/xml/MAIN.SLERT.xml"
```

Validating the same repo without a space in its parent directory works as expected.

**Comment by fsundermeyer** [comment]
Unfortunately there is nothing I can do about this. Actually using file and directory names without spaces is a prerequisite for DAPS.
DAPS is using GNU make which cannot handle spaces in filenames. Workarounds are cumbersome (force you to abandon the use of automatic variables in make, for example).

So, sorry, this is a wontfix.

For more information:
https://www.cmcrossroads.com/article/gnu-make-meets-file-names-spaces-them
