### ISSUE TITLE
AsciiDoc/Attributes capture in rendered output

### ISSUE THREAD

**Issue by bwgartner** [openSUSE/daps#573]
### Problem description
Once engaged with the Documentation-as-Code approach, it is easy to set attributes (via DC and CLI) to provide conditional content. However, unless they are checked in as part of the DC, the resulting output may not be able to be recreated.

### Expected behavior
Much like an autoconf/automake approach, would like the daps command, in the context of source=AsciiDoc/XML/DocBook, to capture/record any/all attributes that were provided (both via DC/CLI) to render the resulting output format. Even if just embedded as comments/metadate in the rendered output, this would be valuable to ensure another pass could consistently render the output.

Of course, just having multiple DC files is an option, but unsure if that is recorded in the generated output either (and suspect versioning may also be relevant in that sense as well).

### Steps to reproduce problem
a) DC file:
ADOC_ATTRIBUTES+=" --attribute foo=1"
ADOC_ATTRIBUTES+=" --attribute bar=1"

b) then daps --force -d <DC> html

c) But then only editing/commenting DC (but not checking in)
ADOC_ATTRIBUTES+=" --attribute foo=0"
or CLI
daps --force -d <DC> --adocattr="attribute bar=0" html

would potentially provide a different, generated, rendered output, but difficult for others to recreate (since not recorded anywhere) if not done by this particular author.

**Comment by fsundermeyer** [comment]
* DAPS could post the "command line" including the DC file parameteers via xslt paramater
* Stylesheets could create and appendix with the contents of that paramneter as text/screen
