### ISSUE TITLE
inkscape 1.0 command line options incompatible with 0.9

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/daps#576]
When having inkscape 1,0 installed, DAPS fails on converting SVG images because inkscape 1.0 uses new command line options and no longer supports the ones from 0.x

**Comment by fsundermeyer** [comment]
Was already fixed with 7f1ec5c9c28e

**Comment by fsundermeyer** [comment]
Also see 7fc57006

**Comment by tomschr** [comment]
@fsundermeyer as this issue was already fixed in the commits above, it make sense to close it.
