### ISSUE TITLE
plans to move past python-xml (version 2.7 based)

### ISSUE THREAD

**Issue by bwgartner** [openSUSE/daps#582]
### Problem description
Still see a "import xml.sax", so maybe a lower level dependency to resolve

### Expected behavior
Given Python v2* EOL, wishing to move completely forward to v3* equivalent

### Steps to reproduce problem
rpm -qillp --requires daps-3.0.0-bp152.4.8.noarch.rpm
...
python-xml
...

and this necessitates:

Repository     : openSUSE:Tumbleweed
Name           : python-xml
Version        : 2.7.18-4.

Repository     : openSUSE:Leap:15.2:Update
Name           : python-xml
Version        : 2.7.17-lp152.3.9.2

SLE 15-SP2
Repository     : SLE-Module-Python2-15-SP2-Updates
Name           : python-xml
Version        : 2.7.17-7.47.1

**Comment by tomschr** [comment]
Thank you @bwgartner for your report! :+1: 

Well, `xml.sax` is a dependency from `python3-base`:

```
$ python3 -c "import xml.sax; print(xml.sax.__file__)"
/usr/lib64/python3.6/xml/sax/__init__.py
$ rpm -qf /usr/lib64/python3.6/xml/sax/__init__.py
python3-base-3.6.12-lp152.4.14.1.x86_64
```

This module is still needed. However, that has nothing to do with Python2. What _does_ have to do is the package `python-xml`. This dependency is indeed unnecessary.

I will remove this dependency in our spec file.
