### ISSUE TITLE
Improve Doc by Inserting a Link to XEP Spec File [sf#60]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#60]
**Reported by tom_schr on 2012-03-23 13:37 UTC**
Enhancement, not a bug:

As discussed with Tanja today, it would be nice if we could improve our documentation especially for XEP users.

As the XEP archive cannot be distributed due to license issues nor the RPM package, it would be interesting to deliver at least the XEP spec file and the xep shell script. Those two files can be distributed under our own license.

For the documentation it would be beneficial to incorporate a link which points to a directory containing these two files. Preferably it points to a directory on our SF SVN. That would allow other, non-openSUSE users to build their own RPM.

Of course, this would work only for RPM-based systems.

**Comment by tomschr** [comment]
**Updated by tom_schr on 2012-03-23 13:39**
- **summary**: Insert Link to XEP Spec File --> Improve Doc by Inserting a Link to XEP Spec File

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2012-03-23 14:04**
I wonder who, apart from large companies, will need to build XEP RPMs. Admins in large companies will know how to do it and the rest of the XEP users will not need it, because the Java Installation routine works fine.

**Comment by tomschr** [comment]
**Commented by tom_schr on 2012-03-23 14:32**
Maybe, maybe not. :) I think it has some advantages, if we recommend users to build a RPM XEP package instead of using a manual installation:
- It's standardized. The XEP script can be found at /usr/bin/xep, not on some arbitrary path
- It is somewhat conformand to our environment. I never fully trust manually installed packages as people can change content unintentionally.
- It doesn't belong to one user

I would use this as a "recommended practise". Of course, people can use other methods if they wish. However, this would be out of scope for the documentation.

**Comment by taroth21** [comment]
Added as idea for a future Development (or Admin) Guide to https://trello.com/c/wiKJY0lW.

**Comment by tomschr** [comment]
Something for a DAPS developer guide.

**Comment by fsundermeyer** [comment]
With FOP having improved over the years, XEP is no longer relevant. WONTFIX
