### ISSUE TITLE
CI: Use an openSUSE Docker container, to improve stability

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#605]
I just ran into an issue where the GitHub Action that we are currently using being unable to download the correct LXML version (apparently it is using slightly outdated package information), which [made the entire CI fail](https://github.com/openSUSE/daps/runs/2278054392).
It would be great to avoid such issues in the future and also test on the primary OS that DAPS will be used on anyway. If we could set up a Docker image for our CI purposes, that might be a good idea.

(CC @tomschr )

**Comment by fsundermeyer** [comment]
This has been fixed a while ago (we are using a docker container).
