### ISSUE TITLE
cleanup: Remove `db5to4` and `db4tonovdoc` stylesheets/targets

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#610]
I don't think there's any reason to continue shipping stylesheets to convert down to DB 4 and to Novdoc. The only way we probably want to convert in the future is DB4->DB5/Geekodoc.

(@tomschr  What do you think?)

**Comment by tomschr** [comment]
Maybe. As I wrote in https://github.com/openSUSE/daps/issues/612#issuecomment-839587944, I would keep them in case we get a DocBook4 document. They don't occupy that much.

**Comment by ghost** [comment]
The stylesheets in the db5to4 directory transform DocBook 5 -> DocBook 4. This is a use case we haven't had since we don't publish via MF anymore. In all likelihood, this use case will not return.

However, the db5to4 stylesheets are still wired up in DAPS, because we used to run them automatically as part of building a TAR archive for MF. And that is what this bug is about.

**Comment by ghost** [comment]
Fixed with c890666.
