### ISSUE TITLE
FALLBACK_STYLEROOT not working as expected

### ISSUE THREAD

**Issue by cwickert** [openSUSE/daps#616]
### Problem description
If STYLEROOT is not present, daps errors out out instead of using FALLBACK_STYLEROOT
```
ERROR: Wrong path for the stylesheet directory
       (provided via config file: STYLEROOT=/usr/share/xml/docbook/stylesheet/suse2021-ns)
```

### Expected behavior
daps should 
* fall back to FALLBACK_STYLEROOT but
* display a warning that STYLEROOT 
  * is not present or
  * does not contain desired outputformat.
* check whether STYLEROOT is a file or directory

Of course one can argue that the fallback should only be used for _missing_ output formats, but a missing directory implies _all_ output formats are missing, so in this case, daps should fall back, too.

### Steps to reproduce problem
* `sudo mv /usr/share/xml/docbook/stylesheet/suse2021-ns /usr/share/xml/docbook/stylesheet/suse2021-ns.back`
* `daps -d DC-SLES-installation validate` = fails with error
* `sudo mkdir /usr/share/xml/docbook/stylesheet/suse2021-ns` = works without any error/warning
* `sudo touch /usr/share/xml/docbook/stylesheet/suse2021-ns` = works, too. daps doesn't check whether it's a file or directory.

**Comment by fsundermeyer** [comment]
If someone explicitly specifies a custom STYLEROOT, they would not expect to get a build with a different stylesheet. A warning message is easily overlooked and likely not seen at all in script context. I think the current behavior is correct, INVALID
