### ISSUE TITLE
/usr/share/daps/make/images.mk in daps should be updated according to the upgrade of inkscape

### ISSUE THREAD

**Issue by tbazant** [openSUSE/daps#626]
### Problem description
see https://bugzilla.suse.com/show_bug.cgi?id=1187250

**Comment by ghost** [comment]
This was fixed in 7f1ec5c9c28edcdee51666b517bdf1863bbb9f77 & 7fc57006832b02ac5d32265a0f19e663cd75b5f1.

The only issue is that the package has not yet been updated in Leap ~~15.2.~~ 15.3.
