### ISSUE TITLE
Add support for SVGBob or mermaid.js?

### ISSUE THREAD

**Issue by tbazant** [openSUSE/daps#636]
### Problem description
Similar to support for DITAA. SVGBob goes much further in what it can draw from text file pictures

see https://github.com/ivanceras/svgbob

[**edit sknorr:**] There is an RPM package here: https://build.opensuse.org/package/show/home:alois/svgbob

**Comment by ghost** [comment]
Another interesting option (Node.js-based and absolutely not RPM-packaged yet): https://mermaid-js.github.io/mermaid/#/

This one is not based upon having to create a lot of whitespace and actually drawing the diagram in text. It is more like a description language for diagrams. This means, _if_ you know what you're doing, creating a diagram may be a lot quicker. You also don't need to work in e.g. org-mode for a comfortable editing experience.
