### ISSUE TITLE
Allow config files for basic stylesheet adjustments [sf#65]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#65]
**Reported by fsundermeyer on 2012-03-27 15:06 UTC**
The DocBook stylesheets contain a high number of customizable parameters. Values for these parameters can either be set in a customization stylesheet or by passing

```
--stringparam <NAME> <VALUE>
```

to xsltproc.
We should make use of the latter in order to make customization easy for non-stylesheet adepts. A config file with the following content

```
# parameter name
# possible values
# default value
# description
<NAME>=<VALUE>
```

could easily be m maintained by users, be sourced by DAPS and be passed to xsltproc.
Such config files should exist for at least the main output formats (FO, HTML, Webhelp, common).

To avoid variable clashes, using a named array would be a good solutions. Comments are allowed in an array setup:

```
declare -A FOO
FOO=(
 # now comes A
 [A]=1
 # and now B
 [B]=2
)
```

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2013-01-15 15:27**
- **milestone**: 2.0 --> Future

**Comment by tomschr** [comment]
**Updated by tom_schr on 2013-12-03 10:11**
- **labels**:  --> doc

**Comment by fsundermeyer** [comment]
This is now handled by issue #308.
