### ISSUE TITLE
DAPS allows `+=` assignment continuations in DC files even if there was no previous `=` assignment

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#650]
### Problem description

Suppose we have this DC file:
```
MAIN+=book.xml
```

DAPS adds a leading space before line continuation, so this will be interpreted essentially as:
```
MAIN=' book.xml'
```
I.e. there is a leading space within the MAIN attribute and DAPS will fail with:

```
ERROR:  book.xml does not exist or does not reside in /path/to/dir, please check your config
```

This seems a little illogical.

### Expected behavior

I would expect `+=` to _not_ be allowed as the first line and DAPS to be vocal about this not being allowed, e.g.:

```
ERROR: "MAIN+=book.xml" is a += line continuation assignment but there is no previous line that can be continued.
```

(Admittedly, my error message is still pretty bad and too technical.)

**Comment by fsundermeyer** [comment]
Fixed with 23ab481
