### ISSUE TITLE
Final Message Does Not Match With Generated JSP Files [sf#87]

### ISSUE THREAD

**Issue by tomschr** [openSUSE/daps#87]
**Reported by tom_schr on 2012-07-18 06:43 UTC**
Building the JSP output gives me the following output (example for SUSE Manager):

```
Writing /local/doc/opensuse-doc/documents/susemanager/en/build/susemanager-reference/jsp/susemanager-reference/reference/en-US/cha.manager.glossary.jsp for glossary(cha.manager.glossary)
Writing /local/doc/opensuse-doc/documents/susemanager/en/build/susemanager-reference/jsp/susemanager-reference/reference/en-US/index.jsp for book(book.susemanager.ref)
```

However, the final message locates the book in a different place:

```
Find the JSP book at:
/local/doc/opensuse-doc/documents/susemanager/en/build/susemanager-reference/jsp/susemanager-reference/index.jsp
```

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2012-07-18 13:27**
- **status**: open --> needinfo

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2012-07-18 13:27**
Seems that the stylesheet adds "reference/en-US" to the stringparam "base.dir" when writing the results.
From my perspective this is completely unnecessary.

**Comment by tomschr** [comment]
**Commented by tom_schr on 2012-09-19 15:10**
We found, it's caused by the processing instruction <tt>&lt;?dbjsp ?></tt>.

The DocBook stylesheets support a couple of PIs; see the following URL for more information: http://docbook.sourceforge.net/release/xsl/current/doc/pi/pi-html.html

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2012-11-23 13:34**
- **assigned_to**: Frank Sundermeyer --> Thomas Schraitle

**Comment by tomschr** [comment]
**Commented by fsundermeyer on 2012-11-23 13:34**
Sounds like I need a stylesheet to determine the output directory.

tom_schr can you provide one?

Please re-assign to me once you have the stylesheet.

**Comment by tomschr** [comment]
**Updated by fsundermeyer on 2013-01-15 14:33**
- **milestone**: 1.0 --> 2.0

**Comment by tomschr** [comment]
This issue was moved to openSUSE/suse-xsl#8

**Comment by ghost** [comment]
This is indeed a DAPS issue, not a suse-xsl issue. Reopening.

**Comment by fsundermeyer** [comment]
DAPS is only showing the topmost directory as a result now, in this case that would be
/local/doc/opensuse-doc/documents/susemanager/en/build/susemanager-reference/jsp/susemanager-reference/
